/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OpenLedgerClient from "../../../../../api/index";
import * as core from "../../../../../core";
import { SandboxRequestPreferences } from "../../types/SandboxRequestPreferences";

export const SandboxRequest: core.serialization.Schema<
    serializers.SandboxRequest.Raw,
    OpenLedgerClient.SandboxRequest
> = core.serialization.object({
    name: core.serialization.string(),
    developerId: core.serialization.property("developer_id", core.serialization.string()),
    industry: core.serialization.string().optional(),
    preferences: SandboxRequestPreferences.optional(),
});

export declare namespace SandboxRequest {
    interface Raw {
        name: string;
        developer_id: string;
        industry?: string | null;
        preferences?: SandboxRequestPreferences.Raw | null;
    }
}
