/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const GetReportsFinancialRequestType: core.serialization.Schema<
    serializers.GetReportsFinancialRequestType.Raw,
    OpenLedgerClient.GetReportsFinancialRequestType
> = core.serialization.enum_(["balance_sheet", "income_statement", "cash_flow"]);

export declare namespace GetReportsFinancialRequestType {
    export type Raw = "balance_sheet" | "income_statement" | "cash_flow";
}
