/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const GetV1ReportsGenerateResponseCashFlowStatementHierarchicalInvestingActivities: core.serialization.ObjectSchema<
    serializers.GetV1ReportsGenerateResponseCashFlowStatementHierarchicalInvestingActivities.Raw,
    OpenLedgerClient.GetV1ReportsGenerateResponseCashFlowStatementHierarchicalInvestingActivities
> = core.serialization.object({
    purchaseOfFixedAssets: core.serialization.number().optional(),
    purchaseOfInvestments: core.serialization.number().optional(),
    saleOfInvestments: core.serialization.number().optional(),
});

export declare namespace GetV1ReportsGenerateResponseCashFlowStatementHierarchicalInvestingActivities {
    export interface Raw {
        purchaseOfFixedAssets?: number | null;
        purchaseOfInvestments?: number | null;
        saleOfInvestments?: number | null;
    }
}
