/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const GetV1ReportsGenerateResponseReconciliation: core.serialization.ObjectSchema<
    serializers.GetV1ReportsGenerateResponseReconciliation.Raw,
    OpenLedgerClient.GetV1ReportsGenerateResponseReconciliation
> = core.serialization.object({
    plaidAccountsTotal: core.serialization.number().optional(),
    ledgerCashBalance: core.serialization.number().optional(),
    difference: core.serialization.number().optional(),
    plaidAccounts: core.serialization.list(core.serialization.unknown()).optional(),
});

export declare namespace GetV1ReportsGenerateResponseReconciliation {
    export interface Raw {
        plaidAccountsTotal?: number | null;
        ledgerCashBalance?: number | null;
        difference?: number | null;
        plaidAccounts?: unknown[] | null;
    }
}
