/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const GetV1ReportsGenerateResponseCashFlowStatementHierarchicalOperatingActivitiesAdjustments: core.serialization.ObjectSchema<
    serializers.GetV1ReportsGenerateResponseCashFlowStatementHierarchicalOperatingActivitiesAdjustments.Raw,
    OpenLedgerClient.GetV1ReportsGenerateResponseCashFlowStatementHierarchicalOperatingActivitiesAdjustments
> = core.serialization.object({
    depreciation: core.serialization.number().optional(),
    changeInAccountsReceivable: core.serialization.number().optional(),
    changeInInventory: core.serialization.number().optional(),
    changeInAccountsPayable: core.serialization.number().optional(),
    changeInAccruedLiabilities: core.serialization.number().optional(),
});

export declare namespace GetV1ReportsGenerateResponseCashFlowStatementHierarchicalOperatingActivitiesAdjustments {
    export interface Raw {
        depreciation?: number | null;
        changeInAccountsReceivable?: number | null;
        changeInInventory?: number | null;
        changeInAccountsPayable?: number | null;
        changeInAccruedLiabilities?: number | null;
    }
}
