/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const GetV1ReportsGeneralLedgerResponseHierarchy: core.serialization.ObjectSchema<
    serializers.GetV1ReportsGeneralLedgerResponseHierarchy.Raw,
    OpenLedgerClient.GetV1ReportsGeneralLedgerResponseHierarchy
> = core.serialization.object({
    assets: core.serialization.list(core.serialization.unknown()).optional(),
    liabilities: core.serialization.list(core.serialization.unknown()).optional(),
    equity: core.serialization.list(core.serialization.unknown()).optional(),
    revenue: core.serialization.list(core.serialization.unknown()).optional(),
    expenses: core.serialization.list(core.serialization.unknown()).optional(),
});

export declare namespace GetV1ReportsGeneralLedgerResponseHierarchy {
    export interface Raw {
        assets?: unknown[] | null;
        liabilities?: unknown[] | null;
        equity?: unknown[] | null;
        revenue?: unknown[] | null;
        expenses?: unknown[] | null;
    }
}
