/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";
import { GetV1ReportsGenerateResponseIncomeStatementHierarchical } from "./GetV1ReportsGenerateResponseIncomeStatementHierarchical";

export const GetV1ReportsGenerateResponseIncomeStatement: core.serialization.ObjectSchema<
    serializers.GetV1ReportsGenerateResponseIncomeStatement.Raw,
    OpenLedgerClient.GetV1ReportsGenerateResponseIncomeStatement
> = core.serialization.object({
    hierarchical: GetV1ReportsGenerateResponseIncomeStatementHierarchical.optional(),
    revenue: core.serialization.number().optional(),
    expenses: core.serialization.number().optional(),
    grossProfit: core.serialization.number().optional(),
    operatingIncome: core.serialization.number().optional(),
    incomeBeforeTax: core.serialization.number().optional(),
    netIncome: core.serialization.number().optional(),
});

export declare namespace GetV1ReportsGenerateResponseIncomeStatement {
    export interface Raw {
        hierarchical?: GetV1ReportsGenerateResponseIncomeStatementHierarchical.Raw | null;
        revenue?: number | null;
        expenses?: number | null;
        grossProfit?: number | null;
        operatingIncome?: number | null;
        incomeBeforeTax?: number | null;
        netIncome?: number | null;
    }
}
