/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";
import { GetV1ReportsOverviewResponseFilterInfoStatusFilter } from "./GetV1ReportsOverviewResponseFilterInfoStatusFilter";
import { GetV1ReportsOverviewResponseFilterInfoDateRange } from "./GetV1ReportsOverviewResponseFilterInfoDateRange";
import { GetV1ReportsOverviewResponseFilterInfoInterval } from "./GetV1ReportsOverviewResponseFilterInfoInterval";

export const GetV1ReportsOverviewResponseFilterInfo: core.serialization.ObjectSchema<
    serializers.GetV1ReportsOverviewResponseFilterInfo.Raw,
    OpenLedgerClient.GetV1ReportsOverviewResponseFilterInfo
> = core.serialization.object({
    statusFilter: GetV1ReportsOverviewResponseFilterInfoStatusFilter.optional(),
    dateRange: GetV1ReportsOverviewResponseFilterInfoDateRange.optional(),
    interval: GetV1ReportsOverviewResponseFilterInfoInterval.optional(),
});

export declare namespace GetV1ReportsOverviewResponseFilterInfo {
    export interface Raw {
        statusFilter?: GetV1ReportsOverviewResponseFilterInfoStatusFilter.Raw | null;
        dateRange?: GetV1ReportsOverviewResponseFilterInfoDateRange.Raw | null;
        interval?: GetV1ReportsOverviewResponseFilterInfoInterval.Raw | null;
    }
}
