/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const GetV1ReportsGenerateResponsePdfUrls: core.serialization.ObjectSchema<
    serializers.GetV1ReportsGenerateResponsePdfUrls.Raw,
    OpenLedgerClient.GetV1ReportsGenerateResponsePdfUrls
> = core.serialization.object({
    profitLoss: core.serialization.property("profit_loss", core.serialization.string().optional()),
    balanceSheet: core.serialization.property("balance_sheet", core.serialization.string().optional()),
    cashFlow: core.serialization.property("cash_flow", core.serialization.string().optional()),
});

export declare namespace GetV1ReportsGenerateResponsePdfUrls {
    export interface Raw {
        profit_loss?: string | null;
        balance_sheet?: string | null;
        cash_flow?: string | null;
    }
}
