/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const GetV1ReportsGenerateResponseReportPeriod: core.serialization.ObjectSchema<
    serializers.GetV1ReportsGenerateResponseReportPeriod.Raw,
    OpenLedgerClient.GetV1ReportsGenerateResponseReportPeriod
> = core.serialization.object({
    month: core.serialization.number().optional(),
    year: core.serialization.number().optional(),
    startDate: core.serialization.date().optional(),
    endDate: core.serialization.date().optional(),
});

export declare namespace GetV1ReportsGenerateResponseReportPeriod {
    export interface Raw {
        month?: number | null;
        year?: number | null;
        startDate?: string | null;
        endDate?: string | null;
    }
}
