/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const GetV1ReportsOverviewResponseFilterInfoInterval: core.serialization.Schema<
    serializers.GetV1ReportsOverviewResponseFilterInfoInterval.Raw,
    OpenLedgerClient.GetV1ReportsOverviewResponseFilterInfoInterval
> = core.serialization.enum_(["daily", "weekly", "monthly"]);

export declare namespace GetV1ReportsOverviewResponseFilterInfoInterval {
    export type Raw = "daily" | "weekly" | "monthly";
}
