/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const GetV1ReportsGenerateResponseCashFlowStatementHierarchicalTotals: core.serialization.ObjectSchema<
    serializers.GetV1ReportsGenerateResponseCashFlowStatementHierarchicalTotals.Raw,
    OpenLedgerClient.GetV1ReportsGenerateResponseCashFlowStatementHierarchicalTotals
> = core.serialization.object({
    totalOperatingActivities: core.serialization.number().optional(),
    totalInvestingActivities: core.serialization.number().optional(),
    totalFinancingActivities: core.serialization.number().optional(),
    netChangeInCash: core.serialization.number().optional(),
});

export declare namespace GetV1ReportsGenerateResponseCashFlowStatementHierarchicalTotals {
    export interface Raw {
        totalOperatingActivities?: number | null;
        totalInvestingActivities?: number | null;
        totalFinancingActivities?: number | null;
        netChangeInCash?: number | null;
    }
}
