/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";
import { GetV1ReportsGeneralLedgerResponseAccountsItem } from "./GetV1ReportsGeneralLedgerResponseAccountsItem";
import { GetV1ReportsGeneralLedgerResponseHierarchy } from "./GetV1ReportsGeneralLedgerResponseHierarchy";

export const GetV1ReportsGeneralLedgerResponse: core.serialization.ObjectSchema<
    serializers.GetV1ReportsGeneralLedgerResponse.Raw,
    OpenLedgerClient.GetV1ReportsGeneralLedgerResponse
> = core.serialization.object({
    accounts: core.serialization.list(GetV1ReportsGeneralLedgerResponseAccountsItem).optional(),
    entries: core.serialization
        .list(core.serialization.record(core.serialization.string(), core.serialization.unknown()))
        .optional(),
    pdfUrl: core.serialization.property("pdf_url", core.serialization.string().optional()),
    hierarchy: GetV1ReportsGeneralLedgerResponseHierarchy.optional(),
});

export declare namespace GetV1ReportsGeneralLedgerResponse {
    export interface Raw {
        accounts?: GetV1ReportsGeneralLedgerResponseAccountsItem.Raw[] | null;
        entries?: Record<string, unknown>[] | null;
        pdf_url?: string | null;
        hierarchy?: GetV1ReportsGeneralLedgerResponseHierarchy.Raw | null;
    }
}
