/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";
import { GetV1ReportsGenerateResponseReportPeriod } from "./GetV1ReportsGenerateResponseReportPeriod";
import { GetV1ReportsGenerateResponseBalanceSheet } from "./GetV1ReportsGenerateResponseBalanceSheet";
import { GetV1ReportsGenerateResponseIncomeStatement } from "./GetV1ReportsGenerateResponseIncomeStatement";
import { GetV1ReportsGenerateResponseCashFlowStatement } from "./GetV1ReportsGenerateResponseCashFlowStatement";
import { GetV1ReportsGenerateResponseReconciliation } from "./GetV1ReportsGenerateResponseReconciliation";
import { GetV1ReportsGenerateResponsePdfUrls } from "./GetV1ReportsGenerateResponsePdfUrls";

export const GetV1ReportsGenerateResponse: core.serialization.ObjectSchema<
    serializers.GetV1ReportsGenerateResponse.Raw,
    OpenLedgerClient.GetV1ReportsGenerateResponse
> = core.serialization.object({
    reportPeriod: GetV1ReportsGenerateResponseReportPeriod.optional(),
    balanceSheet: GetV1ReportsGenerateResponseBalanceSheet.optional(),
    incomeStatement: GetV1ReportsGenerateResponseIncomeStatement.optional(),
    cashFlowStatement: GetV1ReportsGenerateResponseCashFlowStatement.optional(),
    reconciliation: GetV1ReportsGenerateResponseReconciliation.optional(),
    accountHierarchy: core.serialization.list(core.serialization.unknown()).optional(),
    pdfUrls: core.serialization.property("pdf_urls", GetV1ReportsGenerateResponsePdfUrls.optional()),
});

export declare namespace GetV1ReportsGenerateResponse {
    export interface Raw {
        reportPeriod?: GetV1ReportsGenerateResponseReportPeriod.Raw | null;
        balanceSheet?: GetV1ReportsGenerateResponseBalanceSheet.Raw | null;
        incomeStatement?: GetV1ReportsGenerateResponseIncomeStatement.Raw | null;
        cashFlowStatement?: GetV1ReportsGenerateResponseCashFlowStatement.Raw | null;
        reconciliation?: GetV1ReportsGenerateResponseReconciliation.Raw | null;
        accountHierarchy?: unknown[] | null;
        pdf_urls?: GetV1ReportsGenerateResponsePdfUrls.Raw | null;
    }
}
