/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const GetV1ReportsOverviewResponseChartDataItem: core.serialization.ObjectSchema<
    serializers.GetV1ReportsOverviewResponseChartDataItem.Raw,
    OpenLedgerClient.GetV1ReportsOverviewResponseChartDataItem
> = core.serialization.object({
    date: core.serialization.string().optional(),
    revenue: core.serialization.property("Revenue", core.serialization.number().optional()),
    expenses: core.serialization.property("Expenses", core.serialization.number().optional()),
    profit: core.serialization.property("Profit", core.serialization.number().optional()),
    value: core.serialization.number().optional(),
});

export declare namespace GetV1ReportsOverviewResponseChartDataItem {
    export interface Raw {
        date?: string | null;
        Revenue?: number | null;
        Expenses?: number | null;
        Profit?: number | null;
        value?: number | null;
    }
}
