/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";
import { GetV1ReportsGeneralLedgerResponseAccountsItemBalance } from "./GetV1ReportsGeneralLedgerResponseAccountsItemBalance";

export const GetV1ReportsGeneralLedgerResponseAccountsItem: core.serialization.ObjectSchema<
    serializers.GetV1ReportsGeneralLedgerResponseAccountsItem.Raw,
    OpenLedgerClient.GetV1ReportsGeneralLedgerResponseAccountsItem
> = core.serialization.object({
    name: core.serialization.string().optional(),
    type: core.serialization.string().optional(),
    financialType: core.serialization.string().optional(),
    accountCode: core.serialization.number().optional(),
    subTypeCode: core.serialization.number().optional(),
    balance: GetV1ReportsGeneralLedgerResponseAccountsItemBalance.optional(),
});

export declare namespace GetV1ReportsGeneralLedgerResponseAccountsItem {
    export interface Raw {
        name?: string | null;
        type?: string | null;
        financialType?: string | null;
        accountCode?: number | null;
        subTypeCode?: number | null;
        balance?: GetV1ReportsGeneralLedgerResponseAccountsItemBalance.Raw | null;
    }
}
