/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const DeleteV1EntitiesResponse: core.serialization.ObjectSchema<
    serializers.DeleteV1EntitiesResponse.Raw,
    OpenLedgerClient.DeleteV1EntitiesResponse
> = core.serialization.object({
    message: core.serialization.string().optional(),
});

export declare namespace DeleteV1EntitiesResponse {
    export interface Raw {
        message?: string | null;
    }
}
