/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const DeleteEntitiesResponse: core.serialization.ObjectSchema<
    serializers.DeleteEntitiesResponse.Raw,
    OpenLedgerClient.DeleteEntitiesResponse
> = core.serialization.object({
    success: core.serialization.boolean().optional(),
    message: core.serialization.string().optional(),
});

export declare namespace DeleteEntitiesResponse {
    export interface Raw {
        success?: boolean | null;
        message?: string | null;
    }
}
