/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const EntityCreateRequestEntityType: core.serialization.Schema<
    serializers.EntityCreateRequestEntityType.Raw,
    OpenLedgerClient.EntityCreateRequestEntityType
> = core.serialization.enum_(["LLC", "CORPORATION", "PARTNERSHIP", "SOLE_PROPRIETORSHIP", "NON_PROFIT"]);

export declare namespace EntityCreateRequestEntityType {
    type Raw = "LLC" | "CORPORATION" | "PARTNERSHIP" | "SOLE_PROPRIETORSHIP" | "NON_PROFIT";
}
