/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const EntityCreateRequestStatus: core.serialization.Schema<
    serializers.EntityCreateRequestStatus.Raw,
    OpenLedgerClient.EntityCreateRequestStatus
> = core.serialization.enum_(["ACTIVE", "INACTIVE"]);

export declare namespace EntityCreateRequestStatus {
    export type Raw = "ACTIVE" | "INACTIVE";
}
