/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const PostV1EntitiesResponseEntity: core.serialization.ObjectSchema<
    serializers.PostV1EntitiesResponseEntity.Raw,
    OpenLedgerClient.PostV1EntitiesResponseEntity
> = core.serialization.object({
    id: core.serialization.string().optional(),
    externalId: core.serialization.string().optional(),
    legalName: core.serialization.string().optional(),
    tin: core.serialization.string().optional(),
    usState: core.serialization.string().optional(),
    entityType: core.serialization.string().optional(),
    phoneNumber: core.serialization.string().optional(),
    developerId: core.serialization.string().optional(),
    clerkId: core.serialization.string().optional(),
    dateCreated: core.serialization.date().optional(),
    googleAuthToken: core.serialization.string().optional(),
    adminUserId: core.serialization.string().optional(),
    addressId: core.serialization.string().optional(),
    phone: core.serialization.string().optional(),
    website: core.serialization.string().optional(),
    logoUrl: core.serialization.string().optional(),
    status: core.serialization.string().optional(),
    subscriptionPlan: core.serialization.string().optional(),
    billingInformation: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    settingsId: core.serialization.string().optional(),
    instanceId: core.serialization.string().optional(),
});

export declare namespace PostV1EntitiesResponseEntity {
    export interface Raw {
        id?: string | null;
        externalId?: string | null;
        legalName?: string | null;
        tin?: string | null;
        usState?: string | null;
        entityType?: string | null;
        phoneNumber?: string | null;
        developerId?: string | null;
        clerkId?: string | null;
        dateCreated?: string | null;
        googleAuthToken?: string | null;
        adminUserId?: string | null;
        addressId?: string | null;
        phone?: string | null;
        website?: string | null;
        logoUrl?: string | null;
        status?: string | null;
        subscriptionPlan?: string | null;
        billingInformation?: Record<string, unknown> | null;
        settingsId?: string | null;
        instanceId?: string | null;
    }
}
