/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";
import { Entity } from "../../../types/Entity";

export const PostEntitiesResponse: core.serialization.ObjectSchema<
    serializers.PostEntitiesResponse.Raw,
    OpenLedgerClient.PostEntitiesResponse
> = core.serialization.object({
    entity: Entity.optional(),
});

export declare namespace PostEntitiesResponse {
    interface Raw {
        entity?: Entity.Raw | null;
    }
}
