/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OpenLedgerClient from "../../../../../api/index";
import * as core from "../../../../../core";

export const PostV1EntitiesAuthGenerateTokenRequest: core.serialization.Schema<
    serializers.PostV1EntitiesAuthGenerateTokenRequest.Raw,
    OpenLedgerClient.PostV1EntitiesAuthGenerateTokenRequest
> = core.serialization.object({
    entityId: core.serialization.string(),
    apiKey: core.serialization.string(),
    developerId: core.serialization.string(),
});

export declare namespace PostV1EntitiesAuthGenerateTokenRequest {
    export interface Raw {
        entityId: string;
        apiKey: string;
        developerId: string;
    }
}
