/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OpenLedgerClient from "../../../../../api/index";
import * as core from "../../../../../core";

export const PostV1EntitiesRequest: core.serialization.Schema<
    serializers.PostV1EntitiesRequest.Raw,
    OpenLedgerClient.PostV1EntitiesRequest
> = core.serialization.object({
    externalId: core.serialization.string().optional(),
    legalName: core.serialization.string().optional(),
    tin: core.serialization.string().optional(),
    usState: core.serialization.string().optional(),
    entityType: core.serialization.string().optional(),
    phoneNumber: core.serialization.string().optional(),
    status: core.serialization.string().optional(),
    developerId: core.serialization.string(),
    clerkId: core.serialization.string().optional(),
    dateCreated: core.serialization.date().optional(),
    instanceId: core.serialization.string().optional(),
});

export declare namespace PostV1EntitiesRequest {
    export interface Raw {
        externalId?: string | null;
        legalName?: string | null;
        tin?: string | null;
        usState?: string | null;
        entityType?: string | null;
        phoneNumber?: string | null;
        status?: string | null;
        developerId: string;
        clerkId?: string | null;
        dateCreated?: string | null;
        instanceId?: string | null;
    }
}
