/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OpenLedgerClient from "../../../../../api/index";
import * as core from "../../../../../core";

export const PutV1EntitiesRequest: core.serialization.Schema<
    serializers.PutV1EntitiesRequest.Raw,
    Omit<OpenLedgerClient.PutV1EntitiesRequest, "entityId">
> = core.serialization.object({
    externalId: core.serialization.string().optional(),
    legalName: core.serialization.string().optional(),
    tin: core.serialization.string().optional(),
    usState: core.serialization.string().optional(),
    entityType: core.serialization.string().optional(),
    phoneNumber: core.serialization.string().optional(),
    status: core.serialization.string().optional(),
});

export declare namespace PutV1EntitiesRequest {
    export interface Raw {
        externalId?: string | null;
        legalName?: string | null;
        tin?: string | null;
        usState?: string | null;
        entityType?: string | null;
        phoneNumber?: string | null;
        status?: string | null;
    }
}
