/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OpenLedgerClient from "../../../../../api/index";
import * as core from "../../../../../core";

export const PostV1DevelopersAuthGenerateTokenRequest: core.serialization.Schema<
    serializers.PostV1DevelopersAuthGenerateTokenRequest.Raw,
    OpenLedgerClient.PostV1DevelopersAuthGenerateTokenRequest
> = core.serialization.object({
    developerId: core.serialization.string(),
    apiKey: core.serialization.string(),
});

export declare namespace PostV1DevelopersAuthGenerateTokenRequest {
    export interface Raw {
        developerId: string;
        apiKey: string;
    }
}
