/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const GetV1CategoriesResponseCategoriesItemType: core.serialization.Schema<
    serializers.GetV1CategoriesResponseCategoriesItemType.Raw,
    OpenLedgerClient.GetV1CategoriesResponseCategoriesItemType
> = core.serialization.enum_(["ASSET", "LIABILITY", "EQUITY", "REVENUE", "EXPENSE"]);

export declare namespace GetV1CategoriesResponseCategoriesItemType {
    export type Raw = "ASSET" | "LIABILITY" | "EQUITY" | "REVENUE" | "EXPENSE";
}
