/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";
import { GetV1CategoriesResponseCategoriesItemType } from "./GetV1CategoriesResponseCategoriesItemType";

export const GetV1CategoriesResponseCategoriesItem: core.serialization.ObjectSchema<
    serializers.GetV1CategoriesResponseCategoriesItem.Raw,
    OpenLedgerClient.GetV1CategoriesResponseCategoriesItem
> = core.serialization.object({
    id: core.serialization.string().optional(),
    instanceId: core.serialization.string().optional(),
    parentAccountId: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    type: GetV1CategoriesResponseCategoriesItemType.optional(),
    financialType: core.serialization.string().optional(),
    isCategory: core.serialization.boolean().optional(),
    code: core.serialization.number().optional(),
    subTypeCode: core.serialization.number().optional(),
    tbAccountId: core.serialization.string().optional(),
    templateNodeId: core.serialization.string().optional(),
    ledgerId: core.serialization.string().optional(),
    entityId: core.serialization.string().optional(),
    createdAt: core.serialization.date().optional(),
    updatedAt: core.serialization.date().optional(),
    topLevel: core.serialization.boolean().optional(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace GetV1CategoriesResponseCategoriesItem {
    export interface Raw {
        id?: string | null;
        instanceId?: string | null;
        parentAccountId?: string | null;
        name?: string | null;
        type?: GetV1CategoriesResponseCategoriesItemType.Raw | null;
        financialType?: string | null;
        isCategory?: boolean | null;
        code?: number | null;
        subTypeCode?: number | null;
        tbAccountId?: string | null;
        templateNodeId?: string | null;
        ledgerId?: string | null;
        entityId?: string | null;
        createdAt?: string | null;
        updatedAt?: string | null;
        topLevel?: boolean | null;
        metadata?: Record<string, unknown> | null;
    }
}
