/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const PostV1CategoriesRequestType: core.serialization.Schema<
    serializers.PostV1CategoriesRequestType.Raw,
    OpenLedgerClient.PostV1CategoriesRequestType
> = core.serialization.enum_(["ASSET", "LIABILITY", "EQUITY", "REVENUE", "EXPENSE"]);

export declare namespace PostV1CategoriesRequestType {
    export type Raw = "ASSET" | "LIABILITY" | "EQUITY" | "REVENUE" | "EXPENSE";
}
