/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         entityId: "entityId"
 *     }
 */
export interface DeleteV1EntitiesRequest {
    /**
     * ID of the entity to delete
     */
    entityId: string;
}
