/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../../index";

/**
 * @example
 *     {
 *         legalName: "legalName"
 *     }
 */
export interface EntityCreateRequest {
    externalId?: string;
    legalName: string;
    tin?: string;
    usState?: string;
    entityType?: OpenLedgerClient.EntityCreateRequestEntityType;
    phoneNumber?: string;
    status?: OpenLedgerClient.EntityCreateRequestStatus;
}
