/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../../index";

/**
 * @example
 *     {
 *         entityId: "entityId"
 *     }
 */
export interface EntityUpdateRequest {
    /**
     * entity ID
     */
    entityId: string;
    legalName?: string;
    tin?: string;
    usState?: string;
    entityType?: OpenLedgerClient.EntityUpdateRequestEntityType;
    phoneNumber?: string;
    status?: OpenLedgerClient.EntityUpdateRequestStatus;
}
