/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         developerId: "{{developerId}}"
 *     }
 */
export interface PostV1EntitiesRequest {
    /** External identifier for the entity */
    externalId?: string;
    /** Legal name of the entity */
    legalName?: string;
    /** Tax Identification Number */
    tin?: string;
    /** US state code */
    usState?: string;
    /** Type of entity */
    entityType?: string;
    /** Contact phone number */
    phoneNumber?: string;
    /** Current status of the entity */
    status?: string;
    /** ID of the developer creating the entity */
    developerId: string;
    /** Clerk ID (alternative to developerId) */
    clerkId?: string;
    /** When the entity was created */
    dateCreated?: Date;
    /** ID of the instance to associate with the entity */
    instanceId?: string;
}
