/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         entityId: "entityId"
 *     }
 */
export interface PutV1EntitiesRequest {
    /**
     * ID of the entity to update
     */
    entityId: string;
    /** External identifier for the entity */
    externalId?: string;
    /** Legal name of the entity */
    legalName?: string;
    /** Tax Identification Number */
    tin?: string;
    /** US state code */
    usState?: string;
    /** Type of entity */
    entityType?: string;
    /** Contact phone number */
    phoneNumber?: string;
    /** Current status of the entity */
    status?: string;
}
