/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         entityId: "entityId",
 *         transactionId: "transactionId"
 *     }
 */
export interface DeleteV1TransactionsRequest {
    /**
     * The ID of the entity that owns the transaction
     */
    entityId: string;
    /**
     * The ID of the transaction to delete
     */
    transactionId: string;
}
