/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../../index";

/**
 * @example
 *     {}
 */
export interface ExportTransactionRequest {
    /**
     * Export format
     */
    format?: OpenLedgerClient.ExportTransactionRequestFormat;
    /**
     * Start date for filtering transactions
     */
    startDate?: string;
    /**
     * End date for filtering transactions
     */
    endDate?: string;
}
