/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         entityId: "entityId",
 *         prompt: "prompt"
 *     }
 */
export interface GetTransactionsChatRequest {
    /**
     * entity ID
     */
    entityId: string;
    /**
     * Natural language prompt
     */
    prompt: string;
}
