/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         entityId: "entityId",
 *         month: "month",
 *         year: "year"
 *     }
 */
export interface GetTransactionsByMonthRequest {
    /**
     * entity ID
     */
    entityId: string;
    /**
     * Month (1-12)
     */
    month: string;
    /**
     * Year (YYYY)
     */
    year: string;
}
