/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         entityId: "entityId",
 *         prompt: "prompt"
 *     }
 */
export interface GetV1TransactionsChatRequest {
    /**
     * The ID of the entity to chat about transactions for
     */
    entityId: string;
    /**
     * The natural language prompt
     */
    prompt: string;
    /**
     * JSON string of conversation history
     */
    history?: string;
    /**
     * JSON string of additional context data
     */
    contextData?: string;
    /**
     * Custom prompt to use instead of the main prompt
     */
    customPrompt?: string;
    /**
     * Whether to stream the response
     */
    stream?: string;
}
