/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         entityId: "entityId"
 *     }
 */
export interface GetV1TransactionsCounterpartiesRequest {
    /**
     * The ID of the entity
     */
    entityId: string;
    /**
     * Cursor for pagination
     */
    cursor?: string;
    /**
     * Number of counterparties per page
     */
    pageSize?: number;
}
