/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         entityId: "entityId"
 *     }
 */
export interface GetV1TransactionsByMonthRequest {
    /**
     * The ID of the entity
     */
    entityId: string;
}
