/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../../index";

/**
 * @example
 *     {
 *         entityId: "entityId",
 *         amount: 1.1,
 *         debitAccountId: "debitAccountId",
 *         creditAccountId: "creditAccountId"
 *     }
 */
export interface PostV1TransactionsRequest {
    /**
     * The ID of the entity to create the transaction for
     */
    entityId: string;
    /** When the transaction occurred (defaults to current time if not provided) */
    date?: Date;
    /** The amount of the transaction */
    amount: number;
    /** The currency of the transaction */
    currency?: string;
    /** Description of the transaction */
    description?: string;
    /** ID of the account to debit */
    debitAccountId: string;
    /** ID of the account to credit */
    creditAccountId: string;
    /** Status of the transaction */
    status?: OpenLedgerClient.PostV1TransactionsRequestStatus;
    /** Additional transaction metadata */
    metadata?: Record<string, unknown>;
}
