/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface PostV1TransactionsEditRequest {
    /** The ID of the transaction to edit */
    id: string;
    /** ID of the account to debit (optional if credit_account_id is provided) */
    debitAccountId?: string;
    /** ID of the account to credit (optional if debit_account_id is provided) */
    creditAccountId?: string;
    /** New description for the transaction */
    description?: string;
}
