/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../../index";

/**
 * @example
 *     {}
 */
export interface SuggestTransactionCategoriesRequest {
    transactions?: OpenLedgerClient.Transaction[];
}
