/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../../index";

/**
 * @example
 *     {
 *         entityId: "entityId",
 *         amount: 1.1,
 *         description: "description",
 *         debitAccountId: "debitAccountId",
 *         creditAccountId: "creditAccountId"
 *     }
 */
export interface TransactionRequest {
    /**
     * entity ID
     */
    entityId: string;
    date?: Date;
    amount: number;
    currency?: string;
    description: string;
    debitAccountId: string;
    creditAccountId: string;
    status?: OpenLedgerClient.TransactionRequestStatus;
    metadata?: Record<string, unknown>;
}
