/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OpenLedgerClient from "../../../../../api/index";
import * as core from "../../../../../core";

export const PostV1TransactionsCategorizeRequest: core.serialization.Schema<
    serializers.PostV1TransactionsCategorizeRequest.Raw,
    Omit<OpenLedgerClient.PostV1TransactionsCategorizeRequest, "entityId">
> = core.serialization.object({
    transactionId: core.serialization.string(),
    categoryId: core.serialization.string(),
});

export declare namespace PostV1TransactionsCategorizeRequest {
    export interface Raw {
        transactionId: string;
        categoryId: string;
    }
}
