/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OpenLedgerClient from "../../../../../api/index";
import * as core from "../../../../../core";
import { PostV1TransactionsRequestStatus } from "../../types/PostV1TransactionsRequestStatus";

export const PostV1TransactionsRequest: core.serialization.Schema<
    serializers.PostV1TransactionsRequest.Raw,
    Omit<OpenLedgerClient.PostV1TransactionsRequest, "entityId">
> = core.serialization.object({
    date: core.serialization.date().optional(),
    amount: core.serialization.number(),
    currency: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    debitAccountId: core.serialization.string(),
    creditAccountId: core.serialization.string(),
    status: PostV1TransactionsRequestStatus.optional(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace PostV1TransactionsRequest {
    export interface Raw {
        date?: string | null;
        amount: number;
        currency?: string | null;
        description?: string | null;
        debitAccountId: string;
        creditAccountId: string;
        status?: PostV1TransactionsRequestStatus.Raw | null;
        metadata?: Record<string, unknown> | null;
    }
}
