/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OpenLedgerClient from "../../../../../api/index";
import * as core from "../../../../../core";

export const PutTransactionsRequest: core.serialization.Schema<
    serializers.PutTransactionsRequest.Raw,
    Omit<OpenLedgerClient.PutTransactionsRequest, "entityId">
> = core.serialization.object({
    transactionId: core.serialization.string(),
});

export declare namespace PutTransactionsRequest {
    export interface Raw {
        transactionId: string;
    }
}
