/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OpenLedgerClient from "../../../../../api/index";
import * as core from "../../../../../core";
import { Transaction } from "../../../../types/Transaction";

export const SuggestTransactionCategoriesRequest: core.serialization.Schema<
    serializers.SuggestTransactionCategoriesRequest.Raw,
    OpenLedgerClient.SuggestTransactionCategoriesRequest
> = core.serialization.object({
    transactions: core.serialization.list(Transaction).optional(),
});

export declare namespace SuggestTransactionCategoriesRequest {
    interface Raw {
        transactions?: Transaction.Raw[] | null;
    }
}
