/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OpenLedgerClient from "../../../../../api/index";
import * as core from "../../../../../core";

export const TransactionCategorizeRequest: core.serialization.Schema<
    serializers.TransactionCategorizeRequest.Raw,
    Omit<OpenLedgerClient.TransactionCategorizeRequest, "entityId">
> = core.serialization.object({
    transactionId: core.serialization.string(),
    categoryId: core.serialization.string(),
});

export declare namespace TransactionCategorizeRequest {
    export interface Raw {
        transactionId: string;
        categoryId: string;
    }
}
