/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../../index";

/**
 * @example
 *     {
 *         name: "name",
 *         developerId: "developer_id"
 *     }
 */
export interface SandboxRequest {
    name: string;
    developerId: string;
    industry?: string;
    preferences?: OpenLedgerClient.SandboxRequestPreferences;
}
