/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const GetV1IntegrationsStatusResponseConnectionsItem: core.serialization.ObjectSchema<
    serializers.GetV1IntegrationsStatusResponseConnectionsItem.Raw,
    OpenLedgerClient.GetV1IntegrationsStatusResponseConnectionsItem
> = core.serialization.object({
    id: core.serialization.string().optional(),
    status: core.serialization.string().optional(),
    type: core.serialization.string().optional(),
});

export declare namespace GetV1IntegrationsStatusResponseConnectionsItem {
    export interface Raw {
        id?: string | null;
        status?: string | null;
        type?: string | null;
    }
}
