/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";
import { GetV1IntegrationsStatusResponseConnectionsItem } from "./GetV1IntegrationsStatusResponseConnectionsItem";

export const GetV1IntegrationsStatusResponse: core.serialization.ObjectSchema<
    serializers.GetV1IntegrationsStatusResponse.Raw,
    OpenLedgerClient.GetV1IntegrationsStatusResponse
> = core.serialization.object({
    connections: core.serialization.list(GetV1IntegrationsStatusResponseConnectionsItem).optional(),
    count: core.serialization.number().optional(),
});

export declare namespace GetV1IntegrationsStatusResponse {
    export interface Raw {
        connections?: GetV1IntegrationsStatusResponseConnectionsItem.Raw[] | null;
        count?: number | null;
    }
}
