/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const PostIntegrationsDisconnectResponse: core.serialization.ObjectSchema<
    serializers.PostIntegrationsDisconnectResponse.Raw,
    OpenLedgerClient.PostIntegrationsDisconnectResponse
> = core.serialization.object({
    success: core.serialization.boolean().optional(),
});

export declare namespace PostIntegrationsDisconnectResponse {
    interface Raw {
        success?: boolean | null;
    }
}
