/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OpenLedgerClient from "../../../../../api/index";
import * as core from "../../../../../core";

export const CreateCategoryRequest: core.serialization.Schema<
    serializers.CreateCategoryRequest.Raw,
    OpenLedgerClient.CreateCategoryRequest
> = core.serialization.object({
    name: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
});

export declare namespace CreateCategoryRequest {
    interface Raw {
        name?: string | null;
        description?: string | null;
    }
}
