/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const GetV1BanksCreateLinkResponse: core.serialization.ObjectSchema<
    serializers.GetV1BanksCreateLinkResponse.Raw,
    OpenLedgerClient.GetV1BanksCreateLinkResponse
> = core.serialization.object({
    linkToken: core.serialization.property("link_token", core.serialization.string().optional()),
    expiration: core.serialization.date().optional(),
    requestId: core.serialization.property("request_id", core.serialization.string().optional()),
    userId: core.serialization.property("user_id", core.serialization.string().optional()),
});

export declare namespace GetV1BanksCreateLinkResponse {
    export interface Raw {
        link_token?: string | null;
        expiration?: string | null;
        request_id?: string | null;
        user_id?: string | null;
    }
}
