/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";
import { GetV1BanksSyncStatusResponseAccountsItemSyncStatus } from "./GetV1BanksSyncStatusResponseAccountsItemSyncStatus";

export const GetV1BanksSyncStatusResponseAccountsItem: core.serialization.ObjectSchema<
    serializers.GetV1BanksSyncStatusResponseAccountsItem.Raw,
    OpenLedgerClient.GetV1BanksSyncStatusResponseAccountsItem
> = core.serialization.object({
    id: core.serialization.string().optional(),
    accountName: core.serialization.string().optional(),
    accountMask: core.serialization.string().optional(),
    syncStatus: GetV1BanksSyncStatusResponseAccountsItemSyncStatus.optional(),
    transactionCount: core.serialization.number().optional(),
});

export declare namespace GetV1BanksSyncStatusResponseAccountsItem {
    export interface Raw {
        id?: string | null;
        accountName?: string | null;
        accountMask?: string | null;
        syncStatus?: GetV1BanksSyncStatusResponseAccountsItemSyncStatus.Raw | null;
        transactionCount?: number | null;
    }
}
