/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetReportsFinancialRequestType = "balance_sheet" | "income_statement" | "cash_flow";
export const GetReportsFinancialRequestType = {
    BalanceSheet: "balance_sheet",
    IncomeStatement: "income_statement",
    CashFlow: "cash_flow",
} as const;
