/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../index";

export interface GetV1ReportsOverviewResponse {
    /** Monthly revenue data points [month, amount] */
    monthlyRevenue?: unknown[][];
    /** Monthly expenses data points [month, amount] */
    monthlyExpenses?: unknown[][];
    /** Monthly profit data points [month, amount] */
    monthlyProfit?: unknown[][];
    /** Monthly cash balance data points [month, amount] */
    monthlyCashBalance?: unknown[][];
    /** Total revenue for the period */
    totalRevenue?: number;
    /** Total expenses for the period */
    totalExpenses?: number;
    /** Total profit for the period */
    totalProfit?: number;
    /** Current cash balance across all accounts */
    currentCashBalance?: number;
    /** Data formatted for charts */
    chartData?: OpenLedgerClient.GetV1ReportsOverviewResponseChartDataItem[];
    latestMonthStats?: OpenLedgerClient.GetV1ReportsOverviewResponseLatestMonthStats;
    /** Connected Plaid accounts */
    plaidAccounts?: OpenLedgerClient.GetV1ReportsOverviewResponsePlaidAccountsItem[];
    filterInfo?: OpenLedgerClient.GetV1ReportsOverviewResponseFilterInfo;
}
