/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../index";

export interface GetV1ReportsOverviewResponsePlaidAccountsItem {
    accountId?: string;
    balances?: OpenLedgerClient.GetV1ReportsOverviewResponsePlaidAccountsItemBalances;
    holderCategory?: string;
    mask?: string;
    name?: string;
    officialName?: string;
    subtype?: string;
    type?: string;
}
