/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetV1ReportsGenerateResponseCashFlowStatementHierarchicalFinancingActivities {
    proceedsFromDebt?: number;
    repaymentOfDebt?: number;
    issuanceOfStock?: number;
    dividendsPaid?: number;
}
