/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../index";

export interface GetV1ReportsGenerateResponse {
    reportPeriod?: OpenLedgerClient.GetV1ReportsGenerateResponseReportPeriod;
    balanceSheet?: OpenLedgerClient.GetV1ReportsGenerateResponseBalanceSheet;
    incomeStatement?: OpenLedgerClient.GetV1ReportsGenerateResponseIncomeStatement;
    cashFlowStatement?: OpenLedgerClient.GetV1ReportsGenerateResponseCashFlowStatement;
    reconciliation?: OpenLedgerClient.GetV1ReportsGenerateResponseReconciliation;
    /** Hierarchical structure of all accounts */
    accountHierarchy?: unknown[];
    pdfUrls?: OpenLedgerClient.GetV1ReportsGenerateResponsePdfUrls;
}
