/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetV1ReportsOverviewResponsePlaidAccountsItemBalances {
    available?: number;
    current?: number;
    isoCurrencyCode?: string;
    limit?: number;
    unofficialCurrencyCode?: string;
}
