/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetV1ReportsGenerateResponseCashFlowStatementHierarchicalOperatingActivitiesAdjustments {
    depreciation?: number;
    changeInAccountsReceivable?: number;
    changeInInventory?: number;
    changeInAccountsPayable?: number;
    changeInAccruedLiabilities?: number;
}
