/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetV1ReportsGeneralLedgerResponseAccountsItemBalance {
    /** Pending debit amount */
    debitsPending?: string;
    /** Posted debit amount */
    debitsPosted?: string;
    /** Pending credit amount */
    creditsPending?: string;
    /** Posted credit amount */
    creditsPosted?: string;
    /** Timestamp of the balance */
    timestamp?: string;
}
