/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetV1ReportsGenerateResponseIncomeStatementHierarchicalTotals {
    totalRevenue?: number;
    totalExpenses?: number;
    netIncome?: number;
}
