/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../index";

export interface GetV1ReportsGenerateResponseIncomeStatement {
    hierarchical?: OpenLedgerClient.GetV1ReportsGenerateResponseIncomeStatementHierarchical;
    revenue?: number;
    expenses?: number;
    grossProfit?: number;
    operatingIncome?: number;
    incomeBeforeTax?: number;
    netIncome?: number;
}
