/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../index";

export interface GetV1ReportsOverviewResponseFilterInfo {
    statusFilter?: OpenLedgerClient.GetV1ReportsOverviewResponseFilterInfoStatusFilter;
    dateRange?: OpenLedgerClient.GetV1ReportsOverviewResponseFilterInfoDateRange;
    interval?: OpenLedgerClient.GetV1ReportsOverviewResponseFilterInfoInterval;
}
