/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../index";

export interface GetV1ReportsGenerateResponseCashFlowStatement {
    hierarchical?: OpenLedgerClient.GetV1ReportsGenerateResponseCashFlowStatementHierarchical;
    netCashFromOperatingActivities?: number;
    netCashFromInvestingActivities?: number;
    netCashFromFinancingActivities?: number;
    netChangeInCash?: number;
}
