/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../index";

export interface GetV1ReportsGeneralLedgerResponseAccountsItem {
    /** Account name */
    name?: string;
    /** Account type */
    type?: string;
    /** Financial classification of the account */
    financialType?: string;
    /** Account code */
    accountCode?: number;
    /** Account subtype code */
    subTypeCode?: number;
    balance?: OpenLedgerClient.GetV1ReportsGeneralLedgerResponseAccountsItemBalance;
}
