/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         entityId: "entityId",
 *         publicToken: "public_token"
 *     }
 */
export interface BankAccountRequest {
    /**
     * entity ID
     */
    entityId: string;
    publicToken: string;
}
