/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         entityId: "ent_123456"
 *     }
 */
export interface GetV1BanksCreateLinkRequest {
    /**
     * The ID of the entity to create the link token for
     */
    entityId: string;
}
