/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         entityId: "ent_123456",
 *         publicToken: "public-sandbox-123456-abcdef"
 *     }
 */
export interface PutV1BanksAccountsRequest {
    /**
     * The ID of the entity to add the bank accounts for
     */
    entityId: string;
    /**
     * The Plaid public token received from the Plaid Link onSuccess callback
     */
    publicToken: string;
}
