/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ExportTransactionResponse {
    /** URL to download the exported file */
    url?: string;
    /** Name of the exported file */
    filename?: string;
    /** Number of transactions exported */
    count?: number;
}
