/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../index";

export interface GetTransactionsByMonthResponse {
    transactions?: OpenLedgerClient.Transaction[];
    /** Total number of transactions */
    totalCount?: number;
    /** Month in YYYY-MM format */
    month?: string;
}
