/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../index";

export interface GetTransactionsChatResponse {
    response?: string;
    transactions?: OpenLedgerClient.Transaction[];
}
