/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetV1TransactionsResponseTransactionsItemStatus = "PENDING" | "POSTED";
export const GetV1TransactionsResponseTransactionsItemStatus = {
    Pending: "PENDING",
    Posted: "POSTED",
} as const;
