/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetV1TransactionsResponseTransactionsItemCreditAccount {
    id?: string;
    name?: string;
    type?: string;
    financialType?: string;
    code?: string;
    subTypeCode?: string;
    isCategory?: boolean;
}
