/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetV1TransactionsResponseTransactionsItemPlaidAccount {
    id?: string;
    name?: string;
    type?: string;
    subtype?: string;
    mask?: string;
    institutionId?: string;
}
