/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../index";

export interface GetV1TransactionsResponse {
    transactions?: OpenLedgerClient.GetV1TransactionsResponseTransactionsItem[];
    nextCursor?: string;
    hasMore?: boolean;
}
