/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetV1TransactionsByMonthResponseItem {
    /** The year of the transactions */
    year?: number;
    /** The month of the transactions (1-12) */
    month?: number;
    /** The net change in balance for the month */
    delta?: number;
}
