/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../index";

export interface GetV1TransactionsResponseTransactionsItem {
    id?: string;
    entityId?: string;
    timestamp?: Date;
    amount?: number;
    currency?: string;
    description?: string;
    debitAccountId?: string;
    creditAccountId?: string;
    status?: OpenLedgerClient.GetV1TransactionsResponseTransactionsItemStatus;
    metadata?: Record<string, unknown>;
    date?: Date;
    transactionDate?: Date;
    accountType?: string;
    financialType?: string;
    category?: string;
    categoryId?: string;
    debitAccount?: OpenLedgerClient.GetV1TransactionsResponseTransactionsItemDebitAccount;
    creditAccount?: OpenLedgerClient.GetV1TransactionsResponseTransactionsItemCreditAccount;
}
