/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetV1TransactionsByMonthResponseItemPlaidAccountBreakdownItem {
    /** Plaid account ID */
    id?: string;
    /** Account name */
    name?: string;
    /** Account number mask */
    mask?: string;
    /** Net change for this account in this month */
    delta?: number;
}
