/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../index";

export interface PostV1TransactionsResponseTransaction {
    /** Unique transaction ID */
    id?: string;
    /** Instance ID if available */
    instanceId?: string;
    /** ID of the entity that owns the transaction */
    entityId?: string;
    /** When the transaction occurred */
    timestamp?: Date;
    /** The amount of the transaction */
    amount?: number;
    /** The currency of the transaction */
    currency?: string;
    /** Description of the transaction */
    description?: string;
    /** ID of the account debited */
    debitAccountId?: string;
    /** ID of the account credited */
    creditAccountId?: string;
    /** Status of the transaction */
    status?: OpenLedgerClient.PostV1TransactionsResponseTransactionStatus;
    /** Additional transaction metadata */
    metadata?: Record<string, unknown>;
    /** When the transaction was created */
    createdAt?: Date;
    /** When the transaction was last updated */
    updatedAt?: Date;
}
