/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PostV1TransactionsSearchResponseTransactionsItem {
    id?: string;
    amount?: number;
    description?: string;
    status?: string;
    timestamp?: Date;
    entityId?: string;
    debitAccountId?: string;
    creditAccountId?: string;
    currency?: string;
    metadata?: Record<string, unknown>;
    createdAt?: Date;
    updatedAt?: Date;
}
