/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Status of the transaction
 */
export type PostV1TransactionsResponseTransactionStatus = "PENDING" | "CLEARED";
export const PostV1TransactionsResponseTransactionStatus = {
    Pending: "PENDING",
    Cleared: "CLEARED",
} as const;
