/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../index";

export interface PostV1TransactionsSearchResponse {
    transactions?: OpenLedgerClient.PostV1TransactionsSearchResponseTransactionsItem[];
    pagination?: OpenLedgerClient.PostV1TransactionsSearchResponsePagination;
}
