/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../index";

export interface PostV1TransactionsEditResponseTransaction {
    id?: string;
    amount?: number;
    description?: string;
    status?: string;
    debitAccount?: OpenLedgerClient.PostV1TransactionsEditResponseTransactionDebitAccount;
    creditAccount?: OpenLedgerClient.PostV1TransactionsEditResponseTransactionCreditAccount;
}
