/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PostV1TransactionsSearchResponsePagination {
    /** Total number of transactions matching the search criteria */
    total?: number;
    /** Current page number */
    page?: number;
    /** Number of items per page */
    limit?: number;
    /** Total number of pages */
    totalPages?: number;
}
