/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../index";

export interface PutTransactionsResponse {
    message?: string;
    transaction?: OpenLedgerClient.Transaction;
}
