/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../index";

export interface PutV1TransactionsApproveResponseResultsItem {
    /** Transaction ID */
    id?: string;
    /** Whether this transaction was approved successfully */
    success?: boolean;
    /** The updated transaction data */
    transaction?: OpenLedgerClient.PutV1TransactionsApproveResponseResultsItemTransaction;
    /** Error message if the approval failed */
    error?: string;
}
