/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../index";

export type PutV1TransactionsApproveRequestBody =
    /**
     * Single transaction ID as a string */
    | string
    /**
     * Array of transaction IDs */
    | string[]
    /**
     * Array of transaction objects with IDs */
    | OpenLedgerClient.PutV1TransactionsApproveRequestBodyItem[]
    | OpenLedgerClient.PutV1TransactionsApproveRequestBodyId
    | OpenLedgerClient.PutV1TransactionsApproveRequestBodyTransactionIds;
