/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PutV1TransactionsApproveRequestBodyTransactionIds {
    /** Array of transaction IDs to approve in batch */
    transactionIds: string[];
}
