/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../index";

export interface TransactionSearchRequestFilters {
    dateFrom?: string;
    dateTo?: string;
    amountMin?: number;
    amountMax?: number;
    status?: OpenLedgerClient.TransactionSearchRequestFiltersStatus;
}
