/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TransactionSearchRequestFiltersStatus = "PENDING" | "CLEARED";

export const TransactionSearchRequestFiltersStatus = {
    Pending: "PENDING",
    Cleared: "CLEARED",
} as const;
