/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../index";

export interface BankAccountResponse {
    accounts?: OpenLedgerClient.BankAccountResponseAccountsItem[];
}
