/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../index";

export interface Category {
    /** Unique identifier for the category */
    id?: number;
    /** Name of the category */
    name?: string;
    /** Type of the category */
    type?: OpenLedgerClient.CategoryType;
    /** ID of the company */
    companyId?: string;
    /** Account code */
    accountCode?: number;
    /** Sub-type code */
    subTypeCode?: number;
    /** Trial balance ID */
    tbId?: string;
    /** Ledger ID */
    ledgerId?: string;
}
