/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../index";

export interface Company {
    /** Unique identifier for the company */
    id?: string;
    /** External identifier for the company */
    externalId?: string;
    /** Legal name of the company */
    legalName?: string;
    /** Tax identification number */
    tin?: string;
    /** US state where the company is registered */
    usState?: string;
    /** Type of business entity */
    entityType?: OpenLedgerClient.CompanyEntityType;
    /** Contact phone number */
    phoneNumber?: string;
    /** ID of the developer who created this company */
    developerId?: string;
    /** Date when the company was created */
    dateCreated?: Date;
    /** Google authentication token */
    googleAuthToken?: string;
    /** ID of the admin user */
    adminUserId?: number;
    /** ID of the company's address */
    addressId?: number;
    /** Alternative phone number */
    phone?: string;
    /** Company website URL */
    website?: string;
    /** URL to company logo */
    logoUrl?: string;
    /** Current status of the company */
    status?: OpenLedgerClient.CompanyStatus;
    /** Subscription plan of the company */
    subscriptionPlan?: string;
    /** Billing information for the company */
    billingInformation?: string;
    /** ID of the company settings */
    settingsId?: number;
    /** Whether the company is newly created */
    new?: boolean;
    /** Ledger information */
    ledger?: string;
}
