/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Developer {
    /** Unique identifier for the developer */
    id?: string;
    /** Name of the developer */
    name: string;
    /** External identifier for the developer */
    developerId: string;
    /** Date when the developer was created */
    dateCreated?: Date;
    /** Industry the developer operates in */
    industry?: string;
    /** ID of the developer's preferences */
    preferencesId?: number;
    /** API key for the developer */
    apiKey?: string;
}
