/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../index";

export interface DeveloperCreateRequest {
    name: string;
    developerId: string;
    industry?: string;
    preferences?: OpenLedgerClient.DeveloperCreateRequestPreferences;
}
