/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EntityStatus = "ACTIVE" | "INACTIVE";

export const EntityStatus = {
    Active: "ACTIVE",
    Inactive: "INACTIVE",
} as const;
