/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../index";

export interface GeneralLedger {
    accounts?: OpenLedgerClient.GeneralLedgerAccountsItem[];
    entries?: Record<string, unknown>[];
    pdfUrl?: string;
    hierarchy?: Record<string, unknown>;
}
