/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GeneralLedgerAccountsItemBalance {
    debitsPending?: string;
    debitsPosted?: string;
    creditsPending?: string;
    creditsPosted?: string;
}
