/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../index";

export interface PlaidAccount {
    /** Unique identifier for the Plaid account */
    id?: string;
    /** Plaid access token */
    plaidAccessToken?: string;
    /** Plaid item ID */
    plaidItemId?: string;
    /** Plaid institution ID */
    plaidInstitutionId?: string;
    /** Plaid account ID */
    plaidAccountId?: string;
    /** Name of the account */
    accountName?: string;
    /** Type of the account */
    accountType?: string;
    /** Subtype of the account */
    accountSubtype?: string;
    /** Masked account number */
    accountMask?: string;
    /** Date when the account was linked */
    linkedAt?: Date;
    /** Status of the account */
    status?: OpenLedgerClient.PlaidAccountStatus;
    /** ID of the company */
    companyId?: string;
    /** Cursor for pagination */
    cursor?: string;
}
