/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SemanticSearchResponseResultsItem {
    id?: string;
    sourceId?: string;
    sourceType?: string;
    documentType?: string;
    similarity?: number;
    details?: Record<string, unknown>;
}
