/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../index";

export interface ToolCallRequestHistoryItem {
    role?: OpenLedgerClient.ToolCallRequestHistoryItemRole;
    content?: string;
}
