/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TransactionStatus = "PENDING" | "CLEARED";
export const TransactionStatus = {
    Pending: "PENDING",
    Cleared: "CLEARED",
} as const;
