/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Status of the transaction
 */
export type TransactionStatus = "PENDING" | "CLEARED" | "RECONCILED";

export const TransactionStatus = {
    Pending: "PENDING",
    Cleared: "CLEARED",
    Reconciled: "RECONCILED",
} as const;
