/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Status of categorization
 */
export type TransactionCategorizationStatus = "PENDING" | "READY_FOR_INPUT" | "CATEGORIZED";

export const TransactionCategorizationStatus = {
    Pending: "PENDING",
    ReadyForInput: "READY_FOR_INPUT",
    Categorized: "CATEGORIZED",
} as const;
