/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Ledger type of the transaction
 */
export type TransactionLedgerType =
    | "ASSET"
    | "LIABILITY"
    | "EQUITY"
    | "REVENUE"
    | "EXPENSE"
    | "INTEREST_INCOME"
    | "COGS_EXPENSE"
    | "SGA_EXPENSE"
    | "SM_EXPENSE"
    | "RD_EXPENSE"
    | "INTEREST_EXPENSE"
    | "TAX_EXPENSE"
    | "COMMODITY";

export const TransactionLedgerType = {
    Asset: "ASSET",
    Liability: "LIABILITY",
    Equity: "EQUITY",
    Revenue: "REVENUE",
    Expense: "EXPENSE",
    InterestIncome: "INTEREST_INCOME",
    CogsExpense: "COGS_EXPENSE",
    SgaExpense: "SGA_EXPENSE",
    SmExpense: "SM_EXPENSE",
    RdExpense: "RD_EXPENSE",
    InterestExpense: "INTEREST_EXPENSE",
    TaxExpense: "TAX_EXPENSE",
    Commodity: "COMMODITY",
} as const;
