/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Direction of the transaction
 */
export type TransactionDirection = "DEBT" | "CREDIT";

export const TransactionDirection = {
    Debt: "DEBT",
    Credit: "CREDIT",
} as const;
