/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../index";

export interface Transaction {
    id: string;
    amount: number;
    description: string;
    date: string;
    status: OpenLedgerClient.TransactionStatus;
    type: string;
    categoryId?: string;
    debitAccountId: string;
    creditAccountId: string;
    entityId: string;
    metadata?: Record<string, unknown>;
}
