/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const DeleteTransactionsResponse: core.serialization.ObjectSchema<
    serializers.DeleteTransactionsResponse.Raw,
    OpenLedgerClient.DeleteTransactionsResponse
> = core.serialization.object({
    message: core.serialization.string().optional(),
});

export declare namespace DeleteTransactionsResponse {
    interface Raw {
        message?: string | null;
    }
}
