/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const ExportTransactionRequestFormat: core.serialization.Schema<
    serializers.ExportTransactionRequestFormat.Raw,
    OpenLedgerClient.ExportTransactionRequestFormat
> = core.serialization.enum_(["csv", "xlsx", "json"]);

export declare namespace ExportTransactionRequestFormat {
    type Raw = "csv" | "xlsx" | "json";
}
