/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const ExportTransactionResponse: core.serialization.ObjectSchema<
    serializers.ExportTransactionResponse.Raw,
    OpenLedgerClient.ExportTransactionResponse
> = core.serialization.object({
    url: core.serialization.string().optional(),
    filename: core.serialization.string().optional(),
    count: core.serialization.number().optional(),
});

export declare namespace ExportTransactionResponse {
    interface Raw {
        url?: string | null;
        filename?: string | null;
        count?: number | null;
    }
}
