/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const GetV1TransactionsResponseTransactionsItemDebitAccount: core.serialization.ObjectSchema<
    serializers.GetV1TransactionsResponseTransactionsItemDebitAccount.Raw,
    OpenLedgerClient.GetV1TransactionsResponseTransactionsItemDebitAccount
> = core.serialization.object({
    id: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    type: core.serialization.string().optional(),
    financialType: core.serialization.string().optional(),
    code: core.serialization.string().optional(),
    subTypeCode: core.serialization.string().optional(),
    isCategory: core.serialization.boolean().optional(),
});

export declare namespace GetV1TransactionsResponseTransactionsItemDebitAccount {
    export interface Raw {
        id?: string | null;
        name?: string | null;
        type?: string | null;
        financialType?: string | null;
        code?: string | null;
        subTypeCode?: string | null;
        isCategory?: boolean | null;
    }
}
