/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const GetV1TransactionsByMonthResponseItemPlaidAccountBreakdownItem: core.serialization.ObjectSchema<
    serializers.GetV1TransactionsByMonthResponseItemPlaidAccountBreakdownItem.Raw,
    OpenLedgerClient.GetV1TransactionsByMonthResponseItemPlaidAccountBreakdownItem
> = core.serialization.object({
    id: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    mask: core.serialization.string().optional(),
    delta: core.serialization.number().optional(),
});

export declare namespace GetV1TransactionsByMonthResponseItemPlaidAccountBreakdownItem {
    export interface Raw {
        id?: string | null;
        name?: string | null;
        mask?: string | null;
        delta?: number | null;
    }
}
