/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const GetV1TransactionsByMonthResponseItem: core.serialization.ObjectSchema<
    serializers.GetV1TransactionsByMonthResponseItem.Raw,
    OpenLedgerClient.GetV1TransactionsByMonthResponseItem
> = core.serialization.object({
    year: core.serialization.number().optional(),
    month: core.serialization.number().optional(),
    delta: core.serialization.number().optional(),
});

export declare namespace GetV1TransactionsByMonthResponseItem {
    export interface Raw {
        year?: number | null;
        month?: number | null;
        delta?: number | null;
    }
}
