/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const GetV1TransactionsResponseTransactionsItemPlaidAccount: core.serialization.ObjectSchema<
    serializers.GetV1TransactionsResponseTransactionsItemPlaidAccount.Raw,
    OpenLedgerClient.GetV1TransactionsResponseTransactionsItemPlaidAccount
> = core.serialization.object({
    id: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    type: core.serialization.string().optional(),
    subtype: core.serialization.string().optional(),
    mask: core.serialization.string().optional(),
    institutionId: core.serialization.property("institution_id", core.serialization.string().optional()),
});

export declare namespace GetV1TransactionsResponseTransactionsItemPlaidAccount {
    export interface Raw {
        id?: string | null;
        name?: string | null;
        type?: string | null;
        subtype?: string | null;
        mask?: string | null;
        institution_id?: string | null;
    }
}
