/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";
import { GetV1TransactionsResponseTransactionsItem } from "./GetV1TransactionsResponseTransactionsItem";

export const GetV1TransactionsResponse: core.serialization.ObjectSchema<
    serializers.GetV1TransactionsResponse.Raw,
    OpenLedgerClient.GetV1TransactionsResponse
> = core.serialization.object({
    transactions: core.serialization.list(GetV1TransactionsResponseTransactionsItem).optional(),
    nextCursor: core.serialization.string().optional(),
    hasMore: core.serialization.boolean().optional(),
});

export declare namespace GetV1TransactionsResponse {
    export interface Raw {
        transactions?: GetV1TransactionsResponseTransactionsItem.Raw[] | null;
        nextCursor?: string | null;
        hasMore?: boolean | null;
    }
}
