/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const GetV1TransactionsChatResponse: core.serialization.ObjectSchema<
    serializers.GetV1TransactionsChatResponse.Raw,
    OpenLedgerClient.GetV1TransactionsChatResponse
> = core.serialization.object({
    content: core.serialization.string().optional(),
    parsed: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace GetV1TransactionsChatResponse {
    export interface Raw {
        content?: string | null;
        parsed?: Record<string, unknown> | null;
    }
}
