/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";
import { GetV1TransactionsByMonthResponseItemPlaidAccountBreakdownItem } from "./GetV1TransactionsByMonthResponseItemPlaidAccountBreakdownItem";

export const GetV1TransactionsByMonthResponseItem: core.serialization.ObjectSchema<
    serializers.GetV1TransactionsByMonthResponseItem.Raw,
    OpenLedgerClient.GetV1TransactionsByMonthResponseItem
> = core.serialization.object({
    year: core.serialization.number().optional(),
    month: core.serialization.number().optional(),
    delta: core.serialization.number().optional(),
    plaidAccountBreakdown: core.serialization
        .list(GetV1TransactionsByMonthResponseItemPlaidAccountBreakdownItem)
        .optional(),
});

export declare namespace GetV1TransactionsByMonthResponseItem {
    export interface Raw {
        year?: number | null;
        month?: number | null;
        delta?: number | null;
        plaidAccountBreakdown?: GetV1TransactionsByMonthResponseItemPlaidAccountBreakdownItem.Raw[] | null;
    }
}
