/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";
import { GetV1TransactionsCounterpartiesResponseCounterpartiesItem } from "./GetV1TransactionsCounterpartiesResponseCounterpartiesItem";

export const GetV1TransactionsCounterpartiesResponse: core.serialization.ObjectSchema<
    serializers.GetV1TransactionsCounterpartiesResponse.Raw,
    OpenLedgerClient.GetV1TransactionsCounterpartiesResponse
> = core.serialization.object({
    success: core.serialization.boolean().optional(),
    counterparties: core.serialization.list(GetV1TransactionsCounterpartiesResponseCounterpartiesItem).optional(),
    nextCursor: core.serialization.string().optional(),
    hasMore: core.serialization.boolean().optional(),
});

export declare namespace GetV1TransactionsCounterpartiesResponse {
    export interface Raw {
        success?: boolean | null;
        counterparties?: GetV1TransactionsCounterpartiesResponseCounterpartiesItem.Raw[] | null;
        nextCursor?: string | null;
        hasMore?: boolean | null;
    }
}
