/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const GetV1TransactionsCounterpartiesResponseCounterpartiesItemTransactionsItem: core.serialization.ObjectSchema<
    serializers.GetV1TransactionsCounterpartiesResponseCounterpartiesItemTransactionsItem.Raw,
    OpenLedgerClient.GetV1TransactionsCounterpartiesResponseCounterpartiesItemTransactionsItem
> = core.serialization.object({
    id: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    amount: core.serialization.number().optional(),
    timestamp: core.serialization.date().optional(),
});

export declare namespace GetV1TransactionsCounterpartiesResponseCounterpartiesItemTransactionsItem {
    export interface Raw {
        id?: string | null;
        description?: string | null;
        amount?: number | null;
        timestamp?: string | null;
    }
}
