/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";
import { PostV1TransactionsResponseTransaction } from "./PostV1TransactionsResponseTransaction";

export const PostV1TransactionsResponse: core.serialization.ObjectSchema<
    serializers.PostV1TransactionsResponse.Raw,
    OpenLedgerClient.PostV1TransactionsResponse
> = core.serialization.object({
    transaction: PostV1TransactionsResponseTransaction.optional(),
});

export declare namespace PostV1TransactionsResponse {
    export interface Raw {
        transaction?: PostV1TransactionsResponseTransaction.Raw | null;
    }
}
