/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";
import { PostV1TransactionsEditResponseTransaction } from "./PostV1TransactionsEditResponseTransaction";

export const PostV1TransactionsEditResponse: core.serialization.ObjectSchema<
    serializers.PostV1TransactionsEditResponse.Raw,
    OpenLedgerClient.PostV1TransactionsEditResponse
> = core.serialization.object({
    transaction: PostV1TransactionsEditResponseTransaction.optional(),
    updateResult: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace PostV1TransactionsEditResponse {
    export interface Raw {
        transaction?: PostV1TransactionsEditResponseTransaction.Raw | null;
        updateResult?: Record<string, unknown> | null;
    }
}
