/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const PostV1TransactionsCategorizeResponseTransactionMetadata: core.serialization.ObjectSchema<
    serializers.PostV1TransactionsCategorizeResponseTransactionMetadata.Raw,
    OpenLedgerClient.PostV1TransactionsCategorizeResponseTransactionMetadata
> = core.serialization.object({
    categoryId: core.serialization.string().optional(),
    categoryName: core.serialization.string().optional(),
});

export declare namespace PostV1TransactionsCategorizeResponseTransactionMetadata {
    export interface Raw {
        categoryId?: string | null;
        categoryName?: string | null;
    }
}
