/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";
import { PostV1TransactionsCategorizeResponseTransaction } from "./PostV1TransactionsCategorizeResponseTransaction";

export const PostV1TransactionsCategorizeResponse: core.serialization.ObjectSchema<
    serializers.PostV1TransactionsCategorizeResponse.Raw,
    OpenLedgerClient.PostV1TransactionsCategorizeResponse
> = core.serialization.object({
    message: core.serialization.string().optional(),
    transaction: PostV1TransactionsCategorizeResponseTransaction.optional(),
});

export declare namespace PostV1TransactionsCategorizeResponse {
    export interface Raw {
        message?: string | null;
        transaction?: PostV1TransactionsCategorizeResponseTransaction.Raw | null;
    }
}
