/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";
import { Transaction } from "../../../types/Transaction";
import { PostTransactionsSearchResponsePagination } from "./PostTransactionsSearchResponsePagination";

export const PostTransactionsSearchResponse: core.serialization.ObjectSchema<
    serializers.PostTransactionsSearchResponse.Raw,
    OpenLedgerClient.PostTransactionsSearchResponse
> = core.serialization.object({
    transactions: core.serialization.list(Transaction).optional(),
    pagination: PostTransactionsSearchResponsePagination.optional(),
});

export declare namespace PostTransactionsSearchResponse {
    interface Raw {
        transactions?: Transaction.Raw[] | null;
        pagination?: PostTransactionsSearchResponsePagination.Raw | null;
    }
}
