/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const PostV1TransactionsSearchRequestFilters: core.serialization.ObjectSchema<
    serializers.PostV1TransactionsSearchRequestFilters.Raw,
    OpenLedgerClient.PostV1TransactionsSearchRequestFilters
> = core.serialization.object({
    dateFrom: core.serialization.string().optional(),
    dateTo: core.serialization.string().optional(),
    amountMin: core.serialization.number().optional(),
    amountMax: core.serialization.number().optional(),
    status: core.serialization.string().optional(),
});

export declare namespace PostV1TransactionsSearchRequestFilters {
    export interface Raw {
        dateFrom?: string | null;
        dateTo?: string | null;
        amountMin?: number | null;
        amountMax?: number | null;
        status?: string | null;
    }
}
