/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const PostV1TransactionsEditResponse: core.serialization.ObjectSchema<
    serializers.PostV1TransactionsEditResponse.Raw,
    OpenLedgerClient.PostV1TransactionsEditResponse
> = core.serialization.object({
    id: core.serialization.string().optional(),
    debitAccountId: core.serialization.property("debit_account_id", core.serialization.number().optional()),
    description: core.serialization.string().optional(),
    creditAccountId: core.serialization.property("credit_account_id", core.serialization.number().optional()),
});

export declare namespace PostV1TransactionsEditResponse {
    export interface Raw {
        id?: string | null;
        debit_account_id?: number | null;
        description?: string | null;
        credit_account_id?: number | null;
    }
}
