/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const PostV1TransactionsResponseTransactionStatus: core.serialization.Schema<
    serializers.PostV1TransactionsResponseTransactionStatus.Raw,
    OpenLedgerClient.PostV1TransactionsResponseTransactionStatus
> = core.serialization.enum_(["PENDING", "CLEARED"]);

export declare namespace PostV1TransactionsResponseTransactionStatus {
    export type Raw = "PENDING" | "CLEARED";
}
