/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";
import { PostV1TransactionsSearchResponseTransactionsItem } from "./PostV1TransactionsSearchResponseTransactionsItem";
import { PostV1TransactionsSearchResponsePagination } from "./PostV1TransactionsSearchResponsePagination";

export const PostV1TransactionsSearchResponse: core.serialization.ObjectSchema<
    serializers.PostV1TransactionsSearchResponse.Raw,
    OpenLedgerClient.PostV1TransactionsSearchResponse
> = core.serialization.object({
    transactions: core.serialization.list(PostV1TransactionsSearchResponseTransactionsItem).optional(),
    pagination: PostV1TransactionsSearchResponsePagination.optional(),
});

export declare namespace PostV1TransactionsSearchResponse {
    export interface Raw {
        transactions?: PostV1TransactionsSearchResponseTransactionsItem.Raw[] | null;
        pagination?: PostV1TransactionsSearchResponsePagination.Raw | null;
    }
}
