/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const PostV1TransactionsEditResponseTransactionDebitAccount: core.serialization.ObjectSchema<
    serializers.PostV1TransactionsEditResponseTransactionDebitAccount.Raw,
    OpenLedgerClient.PostV1TransactionsEditResponseTransactionDebitAccount
> = core.serialization.object({
    id: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
});

export declare namespace PostV1TransactionsEditResponseTransactionDebitAccount {
    export interface Raw {
        id?: string | null;
        name?: string | null;
    }
}
