/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";
import { Transaction } from "../../../types/Transaction";

export const PutTransactionsResponse: core.serialization.ObjectSchema<
    serializers.PutTransactionsResponse.Raw,
    OpenLedgerClient.PutTransactionsResponse
> = core.serialization.object({
    message: core.serialization.string().optional(),
    transaction: Transaction.optional(),
});

export declare namespace PutTransactionsResponse {
    export interface Raw {
        message?: string | null;
        transaction?: Transaction.Raw | null;
    }
}
