/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const PutV1TransactionsApproveRequestBodyId: core.serialization.ObjectSchema<
    serializers.PutV1TransactionsApproveRequestBodyId.Raw,
    OpenLedgerClient.PutV1TransactionsApproveRequestBodyId
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace PutV1TransactionsApproveRequestBodyId {
    export interface Raw {
        id: string;
    }
}
