/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const PutV1TransactionsApproveRequestBodyItem: core.serialization.ObjectSchema<
    serializers.PutV1TransactionsApproveRequestBodyItem.Raw,
    OpenLedgerClient.PutV1TransactionsApproveRequestBodyItem
> = core.serialization.object({
    id: core.serialization.string().optional(),
});

export declare namespace PutV1TransactionsApproveRequestBodyItem {
    export interface Raw {
        id?: string | null;
    }
}
