/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";
import { PutV1TransactionsApproveRequestBodyItem } from "./PutV1TransactionsApproveRequestBodyItem";
import { PutV1TransactionsApproveRequestBodyId } from "./PutV1TransactionsApproveRequestBodyId";
import { PutV1TransactionsApproveRequestBodyTransactionIds } from "./PutV1TransactionsApproveRequestBodyTransactionIds";

export const PutV1TransactionsApproveRequestBody: core.serialization.Schema<
    serializers.PutV1TransactionsApproveRequestBody.Raw,
    OpenLedgerClient.PutV1TransactionsApproveRequestBody
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.list(core.serialization.string()),
    core.serialization.list(PutV1TransactionsApproveRequestBodyItem),
    PutV1TransactionsApproveRequestBodyId,
    PutV1TransactionsApproveRequestBodyTransactionIds,
]);

export declare namespace PutV1TransactionsApproveRequestBody {
    export type Raw =
        | string
        | string[]
        | PutV1TransactionsApproveRequestBodyItem.Raw[]
        | PutV1TransactionsApproveRequestBodyId.Raw
        | PutV1TransactionsApproveRequestBodyTransactionIds.Raw;
}
