/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const PutV1TransactionsApproveResponseResultsItemTransaction: core.serialization.ObjectSchema<
    serializers.PutV1TransactionsApproveResponseResultsItemTransaction.Raw,
    OpenLedgerClient.PutV1TransactionsApproveResponseResultsItemTransaction
> = core.serialization.object({
    id: core.serialization.string().optional(),
    amount: core.serialization.number().optional(),
    description: core.serialization.string().optional(),
    status: core.serialization.string().optional(),
});

export declare namespace PutV1TransactionsApproveResponseResultsItemTransaction {
    export interface Raw {
        id?: string | null;
        amount?: number | null;
        description?: string | null;
        status?: string | null;
    }
}
