/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const PutV1TransactionsApproveRequestBodyTransactionIds: core.serialization.ObjectSchema<
    serializers.PutV1TransactionsApproveRequestBodyTransactionIds.Raw,
    OpenLedgerClient.PutV1TransactionsApproveRequestBodyTransactionIds
> = core.serialization.object({
    transactionIds: core.serialization.list(core.serialization.string()),
});

export declare namespace PutV1TransactionsApproveRequestBodyTransactionIds {
    export interface Raw {
        transactionIds: string[];
    }
}
