/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const SuggestTransactionCategoriesResponseItem: core.serialization.ObjectSchema<
    serializers.SuggestTransactionCategoriesResponseItem.Raw,
    OpenLedgerClient.SuggestTransactionCategoriesResponseItem
> = core.serialization.object({
    transactionId: core.serialization.property("transaction_id", core.serialization.string().optional()),
    suggestedCategories: core.serialization.property(
        "suggested_categories",
        core.serialization.list(core.serialization.string()).optional()
    ),
});

export declare namespace SuggestTransactionCategoriesResponseItem {
    interface Raw {
        transaction_id?: string | null;
        suggested_categories?: string[] | null;
    }
}
