/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const TransactionRequestStatus: core.serialization.Schema<
    serializers.TransactionRequestStatus.Raw,
    OpenLedgerClient.TransactionRequestStatus
> = core.serialization.enum_(["PENDING", "CLEARED"]);

export declare namespace TransactionRequestStatus {
    type Raw = "PENDING" | "CLEARED";
}
