/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of category
 */
export type GetV1CategoriesResponseCategoriesItemType = "ASSET" | "LIABILITY" | "EQUITY" | "REVENUE" | "EXPENSE";
export const GetV1CategoriesResponseCategoriesItemType = {
    Asset: "ASSET",
    Liability: "LIABILITY",
    Equity: "EQUITY",
    Revenue: "REVENUE",
    Expense: "EXPENSE",
} as const;
