/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EntityCreateRequestStatus = "ACTIVE" | "INACTIVE";

export const EntityCreateRequestStatus = {
    Active: "ACTIVE",
    Inactive: "INACTIVE",
} as const;
