/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EntityUpdateRequestEntityType =
    | "LLC"
    | "CORPORATION"
    | "PARTNERSHIP"
    | "SOLE_PROPRIETORSHIP"
    | "NON_PROFIT";

export const EntityUpdateRequestEntityType = {
    Llc: "LLC",
    Corporation: "CORPORATION",
    Partnership: "PARTNERSHIP",
    SoleProprietorship: "SOLE_PROPRIETORSHIP",
    NonProfit: "NON_PROFIT",
} as const;
