/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../index";

export interface GetV1EntitiesResponseEntity {
    /** Unique identifier for the entity */
    id?: string;
    /** Legal name of the entity */
    name?: string;
    /** External identifier for the entity */
    externalId?: string;
    /** Type of entity (e.g., LLC) */
    entityType?: string;
    /** Entity's address information */
    address?: OpenLedgerClient.GetV1EntitiesResponseEntityAddress;
    /** Entity's settings */
    settings?: Record<string, unknown>;
    /** List of connected Plaid accounts */
    plaidAccounts?: OpenLedgerClient.GetV1EntitiesResponseEntityPlaidAccountsItem[];
    /** When the entity was created */
    createdAt?: Date;
    /** ID of the developer who created the entity */
    developerId?: string;
    /** ID of the instance this entity belongs to */
    instanceId?: string;
    /** Current status of the entity */
    status?: string;
}
