/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../index";

export interface GetV1EntitiesResponse {
    entity?: OpenLedgerClient.GetV1EntitiesResponseEntity;
}
