/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetV1EntitiesResponseEntityPlaidAccountsItem {
    /** Unique identifier for the Plaid account */
    id?: string;
    /** Plaid access token for the account */
    plaidAccessToken?: string;
    /** Plaid item ID */
    plaidItemId?: string;
    /** Plaid institution ID */
    plaidInstitutionId?: string;
    /** Plaid account ID */
    plaidAccountId?: string;
    /** Name of the bank account */
    accountName?: string;
    /** Type of the bank account */
    accountType?: string;
    /** Subtype of the bank account */
    accountSubtype?: string;
    /** Last 4 digits of the account number */
    accountMask?: string;
    /** When the account was linked */
    linkedAt?: Date;
    /** Status of the account */
    status?: string;
    /** ID of the entity this account belongs to */
    entityId?: string;
    /** Plaid cursor for syncing */
    cursor?: string;
    /** Whether the account needs initial sync */
    needsInitialSync?: boolean;
}
