/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PostV1EntitiesResponseEntity {
    /** Unique identifier for the created entity */
    id?: string;
    /** External identifier for the entity */
    externalId?: string;
    /** Legal name of the entity */
    legalName?: string;
    /** Tax Identification Number */
    tin?: string;
    /** US state code */
    usState?: string;
    /** Type of entity */
    entityType?: string;
    /** Contact phone number */
    phoneNumber?: string;
    /** ID of the developer who created the entity */
    developerId?: string;
    /** Clerk ID if provided */
    clerkId?: string;
    /** When the entity was created */
    dateCreated?: Date;
    /** Google authentication token if available */
    googleAuthToken?: string;
    /** Admin user ID if assigned */
    adminUserId?: string;
    /** Address ID if available */
    addressId?: string;
    /** Alternative phone number */
    phone?: string;
    /** Entity's website URL */
    website?: string;
    /** URL to entity's logo */
    logoUrl?: string;
    /** Current status of the entity */
    status?: string;
    /** Subscription plan details */
    subscriptionPlan?: string;
    /** Billing information */
    billingInformation?: Record<string, unknown>;
    /** Settings ID if available */
    settingsId?: string;
    /** ID of the instance this entity belongs to */
    instanceId?: string;
}
