/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../index";

export interface PostV1EntitiesResponse {
    entity?: OpenLedgerClient.PostV1EntitiesResponseEntity;
}
