/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         entityId: "entityId"
 *     }
 */
export interface GetIntegrationsStatusRequest {
    /**
     * entity ID
     */
    entityId: string;
}
