/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         entityId: "entityId",
 *         integrationId: "integrationId"
 *     }
 */
export interface IntegrationDisconnectRequest {
    /**
     * entity ID
     */
    entityId: string;
    integrationId: string;
}
