/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         entityId: "entityId",
 *         provider: "provider",
 *         authorization: {
 *             "key": "value"
 *         }
 *     }
 */
export interface IntegrationConnectRequest {
    /**
     * entity ID
     */
    entityId: string;
    provider: string;
    authorization: Record<string, unknown>;
}
