/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         entityId: "entityId",
 *         integrationType: "integrationType"
 *     }
 */
export interface PostV1IntegrationsDisconnectRequest {
    /** The ID of the entity that owns the integration */
    entityId: string;
    /** The type of integration to disconnect (must match connectionType in Unified Connections) */
    integrationType: string;
}
