/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OpenLedgerClient from "../../../../../api/index";
import * as core from "../../../../../core";

export const BankSyncBody: core.serialization.Schema<serializers.BankSyncBody.Raw, OpenLedgerClient.BankSyncBody> =
    core.serialization.object({
        entityId: core.serialization.string(),
    });

export declare namespace BankSyncBody {
    export interface Raw {
        entityId: string;
    }
}
