/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OpenLedgerClient from "../../../../../api/index";
import * as core from "../../../../../core";

export const BankAccountRequest: core.serialization.Schema<
    serializers.BankAccountRequest.Raw,
    Omit<OpenLedgerClient.BankAccountRequest, "entityId">
> = core.serialization.object({
    publicToken: core.serialization.property("public_token", core.serialization.string()),
});

export declare namespace BankAccountRequest {
    export interface Raw {
        public_token: string;
    }
}
