/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         entityId: "entityId",
 *         apiKey: "apiKey",
 *         developerId: "developerId"
 *     }
 */
export interface PostV1AuthEntityTokenRequest {
    /** The ID of the entity */
    entityId: string;
    /** The API key for the entity */
    apiKey: string;
    /** The ID of the developer */
    developerId: string;
}
