/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";

export const PostV1AuthTokensRequestUserType: core.serialization.Schema<
    serializers.PostV1AuthTokensRequestUserType.Raw,
    OpenLedgerClient.PostV1AuthTokensRequestUserType
> = core.serialization.enum_(["developer", "entity", "admin"]);

export declare namespace PostV1AuthTokensRequestUserType {
    export type Raw = "developer" | "entity" | "admin";
}
