/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const BankAccount: core.serialization.ObjectSchema<serializers.BankAccount.Raw, OpenLedgerClient.BankAccount> =
    core.serialization.object({
        id: core.serialization.string(),
        accountName: core.serialization.string(),
        accountType: core.serialization.string(),
        accountMask: core.serialization.string(),
    });

export declare namespace BankAccount {
    export interface Raw {
        id: string;
        accountName: string;
        accountType: string;
        accountMask: string;
    }
}
