/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";
import { BankAccountResponseAccountsItem } from "./BankAccountResponseAccountsItem";

export const BankAccountResponse: core.serialization.ObjectSchema<
    serializers.BankAccountResponse.Raw,
    OpenLedgerClient.BankAccountResponse
> = core.serialization.object({
    accounts: core.serialization.list(BankAccountResponseAccountsItem).optional(),
});

export declare namespace BankAccountResponse {
    export interface Raw {
        accounts?: BankAccountResponseAccountsItem.Raw[] | null;
    }
}
