/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const BankAccountAddRequest: core.serialization.ObjectSchema<
    serializers.BankAccountAddRequest.Raw,
    OpenLedgerClient.BankAccountAddRequest
> = core.serialization.object({
    entityId: core.serialization.string(),
    publicToken: core.serialization.property("public_token", core.serialization.string()),
});

export declare namespace BankAccountAddRequest {
    export interface Raw {
        entityId: string;
        public_token: string;
    }
}
