/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";
import { CategoryType } from "./CategoryType";

export const Category: core.serialization.ObjectSchema<serializers.Category.Raw, OpenLedgerClient.Category> =
    core.serialization.object({
        id: core.serialization.number().optional(),
        name: core.serialization.string().optional(),
        type: CategoryType.optional(),
        companyId: core.serialization.string().optional(),
        accountCode: core.serialization.property("account_code", core.serialization.number().optional()),
        subTypeCode: core.serialization.property("sub_type_code", core.serialization.number().optional()),
        tbId: core.serialization.property("tb_id", core.serialization.string().optional()),
        ledgerId: core.serialization.property("ledger_id", core.serialization.string().optional()),
    });

export declare namespace Category {
    interface Raw {
        id?: number | null;
        name?: string | null;
        type?: CategoryType.Raw | null;
        companyId?: string | null;
        account_code?: number | null;
        sub_type_code?: number | null;
        tb_id?: string | null;
        ledger_id?: string | null;
    }
}
