/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const CategoryCreateRequest: core.serialization.ObjectSchema<
    serializers.CategoryCreateRequest.Raw,
    OpenLedgerClient.CategoryCreateRequest
> = core.serialization.object({
    name: core.serialization.string(),
    type: core.serialization.string(),
    accountCode: core.serialization.string().optional(),
    subTypeCode: core.serialization.string().optional(),
});

export declare namespace CategoryCreateRequest {
    export interface Raw {
        name: string;
        type: string;
        accountCode?: string | null;
        subTypeCode?: string | null;
    }
}
