/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const CompanyStatus: core.serialization.Schema<serializers.CompanyStatus.Raw, OpenLedgerClient.CompanyStatus> =
    core.serialization.enum_(["ACTIVE", "INACTIVE"]);

export declare namespace CompanyStatus {
    type Raw = "ACTIVE" | "INACTIVE";
}
