/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const DeveloperCreateRequestPreferences: core.serialization.ObjectSchema<
    serializers.DeveloperCreateRequestPreferences.Raw,
    OpenLedgerClient.DeveloperCreateRequestPreferences
> = core.serialization.object({
    currency: core.serialization.string(),
    timezone: core.serialization.string(),
    locale: core.serialization.string(),
});

export declare namespace DeveloperCreateRequestPreferences {
    export interface Raw {
        currency: string;
        timezone: string;
        locale: string;
    }
}
