/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const Developer: core.serialization.ObjectSchema<serializers.Developer.Raw, OpenLedgerClient.Developer> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        name: core.serialization.string(),
        developerId: core.serialization.property("developer_id", core.serialization.string()),
        dateCreated: core.serialization.property("date_created", core.serialization.date().optional()),
        industry: core.serialization.string().optional(),
        preferencesId: core.serialization.property("preferences_id", core.serialization.number().optional()),
        apiKey: core.serialization.property("api_key", core.serialization.string().optional()),
    });

export declare namespace Developer {
    interface Raw {
        id?: string | null;
        name: string;
        developer_id: string;
        date_created?: string | null;
        industry?: string | null;
        preferences_id?: number | null;
        api_key?: string | null;
    }
}
