/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";
import { EntityEntityType } from "./EntityEntityType";
import { EntityStatus } from "./EntityStatus";

export const Entity: core.serialization.ObjectSchema<serializers.Entity.Raw, OpenLedgerClient.Entity> =
    core.serialization.object({
        externalId: core.serialization.string().optional(),
        legalName: core.serialization.string().optional(),
        tin: core.serialization.string().optional(),
        usState: core.serialization.string().optional(),
        entityType: EntityEntityType.optional(),
        phoneNumber: core.serialization.string().optional(),
        clerkId: core.serialization.string().optional(),
        dateCreated: core.serialization.string().optional(),
        status: EntityStatus.optional(),
        instanceId: core.serialization.string().optional(),
        developerId: core.serialization.string().optional(),
        developerId: core.serialization.property("developer_id", core.serialization.string().optional()),
    });

export declare namespace Entity {
    export interface Raw {
        externalId?: string | null;
        legalName?: string | null;
        tin?: string | null;
        usState?: string | null;
        entityType?: EntityEntityType.Raw | null;
        phoneNumber?: string | null;
        clerkId?: string | null;
        dateCreated?: string | null;
        status?: EntityStatus.Raw | null;
        instanceId?: string | null;
        developerId?: string | null;
        developer_id?: string | null;
    }
}
