/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const EntityDetailsQuery: core.serialization.ObjectSchema<
    serializers.EntityDetailsQuery.Raw,
    OpenLedgerClient.EntityDetailsQuery
> = core.serialization.object({
    entityId: core.serialization.string().optional(),
    externalId: core.serialization.string().optional(),
    cursor: core.serialization.string().optional(),
    pageSize: core.serialization.number().optional(),
});

export declare namespace EntityDetailsQuery {
    export interface Raw {
        entityId?: string | null;
        externalId?: string | null;
        cursor?: string | null;
        pageSize?: number | null;
    }
}
