/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const EntityStatus: core.serialization.Schema<serializers.EntityStatus.Raw, OpenLedgerClient.EntityStatus> =
    core.serialization.enum_(["ACTIVE", "INACTIVE"]);

export declare namespace EntityStatus {
    export type Raw = "ACTIVE" | "INACTIVE";
}
