/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const EntityTokenRequest: core.serialization.ObjectSchema<
    serializers.EntityTokenRequest.Raw,
    OpenLedgerClient.EntityTokenRequest
> = core.serialization.object({
    entityId: core.serialization.string(),
    apiKey: core.serialization.string(),
    developerId: core.serialization.string(),
});

export declare namespace EntityTokenRequest {
    export interface Raw {
        entityId: string;
        apiKey: string;
        developerId: string;
    }
}
