/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const FilterCriteriaCriteriaAmount: core.serialization.ObjectSchema<
    serializers.FilterCriteriaCriteriaAmount.Raw,
    OpenLedgerClient.FilterCriteriaCriteriaAmount
> = core.serialization.object({
    min: core.serialization.number().optional(),
    max: core.serialization.number().optional(),
});

export declare namespace FilterCriteriaCriteriaAmount {
    export interface Raw {
        min?: number | null;
        max?: number | null;
    }
}
