/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const FilterCriteriaCriteriaCategory: core.serialization.ObjectSchema<
    serializers.FilterCriteriaCriteriaCategory.Raw,
    OpenLedgerClient.FilterCriteriaCriteriaCategory
> = core.serialization.object({
    includes: core.serialization.list(core.serialization.string()).optional(),
    excludes: core.serialization.list(core.serialization.string()).optional(),
    types: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace FilterCriteriaCriteriaCategory {
    export interface Raw {
        includes?: string[] | null;
        excludes?: string[] | null;
        types?: string[] | null;
    }
}
