/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const FilterCriteriaCriteriaStatus: core.serialization.Schema<
    serializers.FilterCriteriaCriteriaStatus.Raw,
    OpenLedgerClient.FilterCriteriaCriteriaStatus
> = core.serialization.enum_(["PENDING", "CLEARED", "any"]);

export declare namespace FilterCriteriaCriteriaStatus {
    export type Raw = "PENDING" | "CLEARED" | "any";
}
