/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";
import { FinancialReportPdfUrls } from "./FinancialReportPdfUrls";

export const FinancialReport: core.serialization.ObjectSchema<
    serializers.FinancialReport.Raw,
    OpenLedgerClient.FinancialReport
> = core.serialization.object({
    balanceSheet: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    incomeStatement: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    cashFlowStatement: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    pdfUrls: core.serialization.property("pdf_urls", FinancialReportPdfUrls.optional()),
});

export declare namespace FinancialReport {
    interface Raw {
        balanceSheet?: Record<string, unknown> | null;
        incomeStatement?: Record<string, unknown> | null;
        cashFlowStatement?: Record<string, unknown> | null;
        pdf_urls?: FinancialReportPdfUrls.Raw | null;
    }
}
