/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";
import { GeneralLedgerAccountsItemBalance } from "./GeneralLedgerAccountsItemBalance";

export const GeneralLedgerAccountsItem: core.serialization.ObjectSchema<
    serializers.GeneralLedgerAccountsItem.Raw,
    OpenLedgerClient.GeneralLedgerAccountsItem
> = core.serialization.object({
    name: core.serialization.string().optional(),
    type: core.serialization.string().optional(),
    financialType: core.serialization.string().optional(),
    accountCode: core.serialization.number().optional(),
    subTypeCode: core.serialization.number().optional(),
    balance: GeneralLedgerAccountsItemBalance.optional(),
});

export declare namespace GeneralLedgerAccountsItem {
    export interface Raw {
        name?: string | null;
        type?: string | null;
        financialType?: string | null;
        accountCode?: number | null;
        subTypeCode?: number | null;
        balance?: GeneralLedgerAccountsItemBalance.Raw | null;
    }
}
