/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const GeneralLedgerAccountsItemBalance: core.serialization.ObjectSchema<
    serializers.GeneralLedgerAccountsItemBalance.Raw,
    OpenLedgerClient.GeneralLedgerAccountsItemBalance
> = core.serialization.object({
    debitsPending: core.serialization.property("debits_pending", core.serialization.string().optional()),
    debitsPosted: core.serialization.property("debits_posted", core.serialization.string().optional()),
    creditsPending: core.serialization.property("credits_pending", core.serialization.string().optional()),
    creditsPosted: core.serialization.property("credits_posted", core.serialization.string().optional()),
});

export declare namespace GeneralLedgerAccountsItemBalance {
    interface Raw {
        debits_pending?: string | null;
        debits_posted?: string | null;
        credits_pending?: string | null;
        credits_posted?: string | null;
    }
}
