/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";
import { GeneralLedgerAccountsItem } from "./GeneralLedgerAccountsItem";

export const GeneralLedger: core.serialization.ObjectSchema<
    serializers.GeneralLedger.Raw,
    OpenLedgerClient.GeneralLedger
> = core.serialization.object({
    accounts: core.serialization.list(GeneralLedgerAccountsItem).optional(),
    entries: core.serialization
        .list(core.serialization.record(core.serialization.string(), core.serialization.unknown()))
        .optional(),
    pdfUrl: core.serialization.property("pdf_url", core.serialization.string().optional()),
    hierarchy: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace GeneralLedger {
    export interface Raw {
        accounts?: GeneralLedgerAccountsItem.Raw[] | null;
        entries?: Record<string, unknown>[] | null;
        pdf_url?: string | null;
        hierarchy?: Record<string, unknown> | null;
    }
}
