/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const IntegrationStatusResponseIntegrationsItem: core.serialization.ObjectSchema<
    serializers.IntegrationStatusResponseIntegrationsItem.Raw,
    OpenLedgerClient.IntegrationStatusResponseIntegrationsItem
> = core.serialization.object({
    id: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    status: core.serialization.string().optional(),
    lastSync: core.serialization.date().optional(),
});

export declare namespace IntegrationStatusResponseIntegrationsItem {
    interface Raw {
        id?: string | null;
        name?: string | null;
        status?: string | null;
        lastSync?: string | null;
    }
}
