/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const InternalServerErrorBody: core.serialization.ObjectSchema<
    serializers.InternalServerErrorBody.Raw,
    OpenLedgerClient.InternalServerErrorBody
> = core.serialization.object({
    error: core.serialization.string().optional(),
});

export declare namespace InternalServerErrorBody {
    export interface Raw {
        error?: string | null;
    }
}
