/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const LinkTokenResponse: core.serialization.ObjectSchema<
    serializers.LinkTokenResponse.Raw,
    OpenLedgerClient.LinkTokenResponse
> = core.serialization.object({
    linkToken: core.serialization.property("link_token", core.serialization.string().optional()),
    expiration: core.serialization.date().optional(),
});

export declare namespace LinkTokenResponse {
    export interface Raw {
        link_token?: string | null;
        expiration?: string | null;
    }
}
