/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const Preferences: core.serialization.ObjectSchema<serializers.Preferences.Raw, OpenLedgerClient.Preferences> =
    core.serialization.object({
        id: core.serialization.number().optional(),
        currency: core.serialization.string().optional(),
        timezone: core.serialization.string().optional(),
        locale: core.serialization.string().optional(),
    });

export declare namespace Preferences {
    interface Raw {
        id?: number | null;
        currency?: string | null;
        timezone?: string | null;
        locale?: string | null;
    }
}
