/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const QueryFilterRequest: core.serialization.ObjectSchema<
    serializers.QueryFilterRequest.Raw,
    OpenLedgerClient.QueryFilterRequest
> = core.serialization.object({
    message: core.serialization.string().optional(),
});

export declare namespace QueryFilterRequest {
    export interface Raw {
        message?: string | null;
    }
}
