/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const SandboxResponseDataEntity: core.serialization.ObjectSchema<
    serializers.SandboxResponseDataEntity.Raw,
    OpenLedgerClient.SandboxResponseDataEntity
> = core.serialization.object({
    id: core.serialization.string().optional(),
    legalName: core.serialization.property("legal_name", core.serialization.string().optional()),
});

export declare namespace SandboxResponseDataEntity {
    export interface Raw {
        id?: string | null;
        legal_name?: string | null;
    }
}
