/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const SandboxResponseDataDeveloper: core.serialization.ObjectSchema<
    serializers.SandboxResponseDataDeveloper.Raw,
    OpenLedgerClient.SandboxResponseDataDeveloper
> = core.serialization.object({
    id: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    apiKey: core.serialization.string().optional(),
});

export declare namespace SandboxResponseDataDeveloper {
    interface Raw {
        id?: string | null;
        name?: string | null;
        apiKey?: string | null;
    }
}
