/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const SandboxResponseDataPlaidAccountsItemBalance: core.serialization.ObjectSchema<
    serializers.SandboxResponseDataPlaidAccountsItemBalance.Raw,
    OpenLedgerClient.SandboxResponseDataPlaidAccountsItemBalance
> = core.serialization.object({
    available: core.serialization.number().optional(),
    current: core.serialization.number().optional(),
});

export declare namespace SandboxResponseDataPlaidAccountsItemBalance {
    export interface Raw {
        available?: number | null;
        current?: number | null;
    }
}
