/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const SemanticSearchResponseResultsItem: core.serialization.ObjectSchema<
    serializers.SemanticSearchResponseResultsItem.Raw,
    OpenLedgerClient.SemanticSearchResponseResultsItem
> = core.serialization.object({
    id: core.serialization.string().optional(),
    sourceId: core.serialization.property("source_id", core.serialization.string().optional()),
    sourceType: core.serialization.property("source_type", core.serialization.string().optional()),
    documentType: core.serialization.property("document_type", core.serialization.string().optional()),
    similarity: core.serialization.number().optional(),
    details: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace SemanticSearchResponseResultsItem {
    export interface Raw {
        id?: string | null;
        source_id?: string | null;
        source_type?: string | null;
        document_type?: string | null;
        similarity?: number | null;
        details?: Record<string, unknown> | null;
    }
}
