/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const ToolResponseType: core.serialization.Schema<
    serializers.ToolResponseType.Raw,
    OpenLedgerClient.ToolResponseType
> = core.serialization.enum_(["workflow", "singleTool", "noTool"]);

export declare namespace ToolResponseType {
    export type Raw = "workflow" | "singleTool" | "noTool";
}
