/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";
import { ToolCallRequestHistoryItemRole } from "./ToolCallRequestHistoryItemRole";

export const ToolCallRequestHistoryItem: core.serialization.ObjectSchema<
    serializers.ToolCallRequestHistoryItem.Raw,
    OpenLedgerClient.ToolCallRequestHistoryItem
> = core.serialization.object({
    role: ToolCallRequestHistoryItemRole.optional(),
    content: core.serialization.string().optional(),
});

export declare namespace ToolCallRequestHistoryItem {
    export interface Raw {
        role?: ToolCallRequestHistoryItemRole.Raw | null;
        content?: string | null;
    }
}
