/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";
import { ToolCallRequestHistoryItem } from "./ToolCallRequestHistoryItem";

export const ToolCallRequest: core.serialization.ObjectSchema<
    serializers.ToolCallRequest.Raw,
    OpenLedgerClient.ToolCallRequest
> = core.serialization.object({
    message: core.serialization.string().optional(),
    history: core.serialization.list(ToolCallRequestHistoryItem).optional(),
});

export declare namespace ToolCallRequest {
    export interface Raw {
        message?: string | null;
        history?: ToolCallRequestHistoryItem.Raw[] | null;
    }
}
