/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const TransactionApproveRequestId: core.serialization.ObjectSchema<
    serializers.TransactionApproveRequestId.Raw,
    OpenLedgerClient.TransactionApproveRequestId
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace TransactionApproveRequestId {
    export interface Raw {
        id: string;
    }
}
