/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const TransactionApproveRequestItem: core.serialization.ObjectSchema<
    serializers.TransactionApproveRequestItem.Raw,
    OpenLedgerClient.TransactionApproveRequestItem
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace TransactionApproveRequestItem {
    export interface Raw {
        id: string;
    }
}
