/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const TransactionTransactionType: core.serialization.Schema<
    serializers.TransactionTransactionType.Raw,
    OpenLedgerClient.TransactionTransactionType
> = core.serialization.enum_(["INVOICE", "PAYMENT", "BANK_TRANSACTION", "BANK_TRANSACTION_PLAID"]);

export declare namespace TransactionTransactionType {
    type Raw = "INVOICE" | "PAYMENT" | "BANK_TRANSACTION" | "BANK_TRANSACTION_PLAID";
}
