/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const TransactionSearchRequest: core.serialization.ObjectSchema<
    serializers.TransactionSearchRequest.Raw,
    OpenLedgerClient.TransactionSearchRequest
> = core.serialization.object({
    query: core.serialization.string(),
    categories: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace TransactionSearchRequest {
    export interface Raw {
        query: string;
        categories?: string[] | null;
    }
}
