/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const TransactionLedgerType: core.serialization.Schema<
    serializers.TransactionLedgerType.Raw,
    OpenLedgerClient.TransactionLedgerType
> = core.serialization.enum_([
    "ASSET",
    "LIABILITY",
    "EQUITY",
    "REVENUE",
    "EXPENSE",
    "INTEREST_INCOME",
    "COGS_EXPENSE",
    "SGA_EXPENSE",
    "SM_EXPENSE",
    "RD_EXPENSE",
    "INTEREST_EXPENSE",
    "TAX_EXPENSE",
    "COMMODITY",
]);

export declare namespace TransactionLedgerType {
    type Raw =
        | "ASSET"
        | "LIABILITY"
        | "EQUITY"
        | "REVENUE"
        | "EXPENSE"
        | "INTEREST_INCOME"
        | "COGS_EXPENSE"
        | "SGA_EXPENSE"
        | "SM_EXPENSE"
        | "RD_EXPENSE"
        | "INTEREST_EXPENSE"
        | "TAX_EXPENSE"
        | "COMMODITY";
}
