/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";
import { TransactionStatus } from "./TransactionStatus";

export const Transaction: core.serialization.ObjectSchema<serializers.Transaction.Raw, OpenLedgerClient.Transaction> =
    core.serialization.object({
        id: core.serialization.string(),
        amount: core.serialization.number(),
        description: core.serialization.string(),
        date: core.serialization.string(),
        status: TransactionStatus,
        type: core.serialization.string(),
        categoryId: core.serialization.string().optional(),
        debitAccountId: core.serialization.string(),
        creditAccountId: core.serialization.string(),
        entityId: core.serialization.string(),
        metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    });

export declare namespace Transaction {
    export interface Raw {
        id: string;
        amount: number;
        description: string;
        date: string;
        status: TransactionStatus.Raw;
        type: string;
        categoryId?: string | null;
        debitAccountId: string;
        creditAccountId: string;
        entityId: string;
        metadata?: Record<string, unknown> | null;
    }
}
