/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";
import { TransactionApproveRequestItem } from "./TransactionApproveRequestItem";
import { TransactionApproveRequestId } from "./TransactionApproveRequestId";
import { TransactionApproveRequestTransactionIds } from "./TransactionApproveRequestTransactionIds";

export const TransactionApproveRequest: core.serialization.Schema<
    serializers.TransactionApproveRequest.Raw,
    OpenLedgerClient.TransactionApproveRequest
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.list(core.serialization.string()),
    core.serialization.list(TransactionApproveRequestItem),
    TransactionApproveRequestId,
    TransactionApproveRequestTransactionIds,
]);

export declare namespace TransactionApproveRequest {
    export type Raw =
        | string
        | string[]
        | TransactionApproveRequestItem.Raw[]
        | TransactionApproveRequestId.Raw
        | TransactionApproveRequestTransactionIds.Raw;
}
