/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const TransactionStatus: core.serialization.Schema<
    serializers.TransactionStatus.Raw,
    OpenLedgerClient.TransactionStatus
> = core.serialization.enum_(["PENDING", "CLEARED"]);

export declare namespace TransactionStatus {
    export type Raw = "PENDING" | "CLEARED";
}
