/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const TransactionCreateRequestDirection: core.serialization.Schema<
    serializers.TransactionCreateRequestDirection.Raw,
    OpenLedgerClient.TransactionCreateRequestDirection
> = core.serialization.enum_(["CREDIT", "DEBIT"]);

export declare namespace TransactionCreateRequestDirection {
    export type Raw = "CREDIT" | "DEBIT";
}
