/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpenLedgerClient from "../../api/index";
import * as core from "../../core";

export const TransactionApproveRequestTransactionIds: core.serialization.ObjectSchema<
    serializers.TransactionApproveRequestTransactionIds.Raw,
    OpenLedgerClient.TransactionApproveRequestTransactionIds
> = core.serialization.object({
    transactionIds: core.serialization.list(core.serialization.string()),
});

export declare namespace TransactionApproveRequestTransactionIds {
    export interface Raw {
        transactionIds: string[];
    }
}
