/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OpenLedgerClient from "../../../../../api/index";
import * as core from "../../../../../core";

export const IntegrationDisconnectRequest: core.serialization.Schema<
    serializers.IntegrationDisconnectRequest.Raw,
    Omit<OpenLedgerClient.IntegrationDisconnectRequest, "entityId">
> = core.serialization.object({
    integrationId: core.serialization.string(),
});

export declare namespace IntegrationDisconnectRequest {
    interface Raw {
        integrationId: string;
    }
}
