/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OpenLedgerClient from "../../../../../api/index";
import * as core from "../../../../../core";

export const IntegrationConnectRequest: core.serialization.Schema<
    serializers.IntegrationConnectRequest.Raw,
    Omit<OpenLedgerClient.IntegrationConnectRequest, "entityId">
> = core.serialization.object({
    provider: core.serialization.string(),
    authorization: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace IntegrationConnectRequest {
    export interface Raw {
        provider: string;
        authorization: Record<string, unknown>;
    }
}
