/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OpenLedgerClient from "../../../../../api/index";
import * as core from "../../../../../core";

export const PostV1IntegrationsDisconnectRequest: core.serialization.Schema<
    serializers.PostV1IntegrationsDisconnectRequest.Raw,
    OpenLedgerClient.PostV1IntegrationsDisconnectRequest
> = core.serialization.object({
    entityId: core.serialization.string(),
    integrationType: core.serialization.string(),
});

export declare namespace PostV1IntegrationsDisconnectRequest {
    export interface Raw {
        entityId: string;
        integrationType: string;
    }
}
