/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../index";

export interface GetV1BanksSyncStatusResponse {
    accounts?: OpenLedgerClient.GetV1BanksSyncStatusResponseAccountsItem[];
    allSynced?: boolean;
    summary?: OpenLedgerClient.GetV1BanksSyncStatusResponseSummary;
}
