/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../index";

export interface GetV1BanksSyncStatusResponseAccountsItem {
    id?: string;
    accountName?: string;
    accountMask?: string;
    syncStatus?: OpenLedgerClient.GetV1BanksSyncStatusResponseAccountsItemSyncStatus;
    transactionCount?: number;
}
