/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetV1BanksSyncStatusResponseAccountsItemSyncStatus = "pending" | "in_progress" | "completed";
export const GetV1BanksSyncStatusResponseAccountsItemSyncStatus = {
    Pending: "pending",
    InProgress: "in_progress",
    Completed: "completed",
} as const;
