/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetV1BanksSyncStatusResponseSummary {
    total?: number;
    completed?: number;
    inProgress?: number;
    pending?: number;
}
