/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PutV1BanksAccountsResponseCreatedAccountsItem {
    id?: string;
    accountName?: string;
    accountType?: string;
    accountMask?: string;
}
