/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../../index";

/**
 * @example
 *     {
 *         entityId: "entityId"
 *     }
 */
export interface GetV1ReportsOverviewRequest {
    /**
     * The ID of the entity to get the overview for
     */
    entityId: string;
    /**
     * Start date for the report period
     */
    startDate?: Date;
    /**
     * End date for the report period (defaults to current date)
     */
    endDate?: Date;
    /**
     * Time interval for aggregating data
     */
    interval?: OpenLedgerClient.GetV1ReportsOverviewRequestInterval;
    /**
     * Filter transactions by their status
     */
    statusFilter?: OpenLedgerClient.GetV1ReportsOverviewRequestStatusFilter;
}
