/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";
import { Transaction } from "../../../types/Transaction";

export const Request: core.serialization.Schema<
    serializers.transactions.bulkCreateTransactions.Request.Raw,
    OpenLedgerClient.Transaction[]
> = core.serialization.list(Transaction);

export declare namespace Request {
    type Raw = Transaction.Raw[];
}

export const Response: core.serialization.Schema<
    serializers.transactions.bulkCreateTransactions.Response.Raw,
    OpenLedgerClient.Transaction[]
> = core.serialization.list(Transaction);

export declare namespace Response {
    type Raw = Transaction.Raw[];
}
