/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";
import { GetV1TransactionsByMonthResponseItem } from "../types/GetV1TransactionsByMonthResponseItem";

export const Response: core.serialization.Schema<
    serializers.transactions.getTransactionsByMonth.Response.Raw,
    OpenLedgerClient.GetV1TransactionsByMonthResponseItem[]
> = core.serialization.list(GetV1TransactionsByMonthResponseItem);

export declare namespace Response {
    export type Raw = GetV1TransactionsByMonthResponseItem.Raw[];
}
