/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpenLedgerClient from "../../../../api/index";
import * as core from "../../../../core";
import { SuggestTransactionCategoriesResponseItem } from "../types/SuggestTransactionCategoriesResponseItem";

export const Response: core.serialization.Schema<
    serializers.transactions.suggestTransactionCategories.Response.Raw,
    OpenLedgerClient.SuggestTransactionCategoriesResponseItem[]
> = core.serialization.list(SuggestTransactionCategoriesResponseItem);

export declare namespace Response {
    type Raw = SuggestTransactionCategoriesResponseItem.Raw[];
}
