/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OpenLedgerClient from "../../../../../api/index";
import * as core from "../../../../../core";

export const CreateCompanyRequest: core.serialization.Schema<
    serializers.CreateCompanyRequest.Raw,
    OpenLedgerClient.CreateCompanyRequest
> = core.serialization.object({
    legalName: core.serialization.property("legal_name", core.serialization.string().optional()),
    tin: core.serialization.string().optional(),
    usState: core.serialization.property("us_state", core.serialization.string().optional()),
    entityType: core.serialization.property("entity_type", core.serialization.string().optional()),
    phoneNumber: core.serialization.property("phone_number", core.serialization.string().optional()),
    developerId: core.serialization.property("developer_id", core.serialization.string().optional()),
});

export declare namespace CreateCompanyRequest {
    interface Raw {
        legal_name?: string | null;
        tin?: string | null;
        us_state?: string | null;
        entity_type?: string | null;
        phone_number?: string | null;
        developer_id?: string | null;
    }
}
