/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Authentication } from "./api/resources/authentication/client/Client";
import { Transactions } from "./api/resources/transactions/client/Client";
import { Reports } from "./api/resources/reports/client/Client";
import { Banks } from "./api/resources/banks/client/Client";
import { Integrations } from "./api/resources/integrations/client/Client";
import { Entities } from "./api/resources/entities/client/Client";
import { Ai } from "./api/resources/ai/client/Client";
import { Sandbox } from "./api/resources/sandbox/client/Client";

export declare namespace OpenLedgerClientClient {
    interface Options {
        environment?: core.Supplier<environments.OpenLedgerClientEnvironment | string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        fetcher?: core.FetchFunction;
    }

    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
    }
}

export class OpenLedgerClientClient {
    constructor(protected readonly _options: OpenLedgerClientClient.Options = {}) {}

    protected _authentication: Authentication | undefined;

    public get authentication(): Authentication {
        return (this._authentication ??= new Authentication(this._options));
    }

    protected _transactions: Transactions | undefined;

    public get transactions(): Transactions {
        return (this._transactions ??= new Transactions(this._options));
    }

    protected _reports: Reports | undefined;

    public get reports(): Reports {
        return (this._reports ??= new Reports(this._options));
    }

    protected _banks: Banks | undefined;

    public get banks(): Banks {
        return (this._banks ??= new Banks(this._options));
    }

    protected _integrations: Integrations | undefined;

    public get integrations(): Integrations {
        return (this._integrations ??= new Integrations(this._options));
    }

    protected _entities: Entities | undefined;

    public get entities(): Entities {
        return (this._entities ??= new Entities(this._options));
    }

    protected _ai: Ai | undefined;

    public get ai(): Ai {
        return (this._ai ??= new Ai(this._options));
    }

    protected _sandbox: Sandbox | undefined;

    public get sandbox(): Sandbox {
        return (this._sandbox ??= new Sandbox(this._options));
    }
}
