/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const OpenLedgerClientEnvironment = {
    Default: "https://api-staging.openledger.com",
} as const;

export type OpenLedgerClientEnvironment = typeof OpenLedgerClientEnvironment.Default;
