/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../index";

export interface GetV1IntegrationsStatusResponse {
    connections?: OpenLedgerClient.GetV1IntegrationsStatusResponseConnectionsItem[];
    /** Number of connections */
    count?: number;
}
