/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenLedgerClient from "../../../../index";

/**
 * @example
 *     {
 *         entityId: "entityId",
 *         name: "name",
 *         type: "ASSET"
 *     }
 */
export interface PostV1CategoriesRequest {
    /**
     * The ID of the entity to create the category for
     */
    entityId: string;
    /** The name of the category */
    name: string;
    /**
     * The type of category. Must be one of:
     * * ASSET - For asset accounts
     * * LIABILITY - For liability accounts
     * * EQUITY - For equity accounts
     * * REVENUE - For revenue accounts
     * * EXPENSE - For expense accounts
     */
    type: OpenLedgerClient.PostV1CategoriesRequestType;
    /** Optional subtype code for the category */
    subTypeCode?: number;
}
