/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OpenLedgerClient from "../../../../../api/index";
import * as core from "../../../../../core";
import { PostV1AuthTokensRequestUserType } from "../../types/PostV1AuthTokensRequestUserType";

export const PostV1AuthTokensRequest: core.serialization.Schema<
    serializers.PostV1AuthTokensRequest.Raw,
    OpenLedgerClient.PostV1AuthTokensRequest
> = core.serialization.object({
    userType: PostV1AuthTokensRequestUserType,
    id: core.serialization.string(),
    apiKey: core.serialization.string(),
    developerId: core.serialization.string().optional(),
});

export declare namespace PostV1AuthTokensRequest {
    export interface Raw {
        userType: PostV1AuthTokensRequestUserType.Raw;
        id: string;
        apiKey: string;
        developerId?: string | null;
    }
}
