/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OpenLedgerClient from "../../../../../api/index";
import * as core from "../../../../../core";

export const TokenRequest: core.serialization.Schema<serializers.TokenRequest.Raw, OpenLedgerClient.TokenRequest> =
    core.serialization.object({
        clientId: core.serialization.property("client_id", core.serialization.string()),
        clientSecret: core.serialization.property("client_secret", core.serialization.string()),
    });

export declare namespace TokenRequest {
    interface Raw {
        client_id: string;
        client_secret: string;
    }
}
