/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         entityId: "entityId",
 *         query: "query"
 *     }
 */
export interface SemanticSearchRequest {
    entityId: string;
    query: string;
    limit?: number;
    sourceTypes?: string[];
    documentTypes?: string[];
    timeStart?: Date;
    timeEnd?: Date;
}
